### ISSUE TITLE
select_by_face_quality() select_by_vertex_quality() crash

### ISSUE THREAD

**Issue by Cervidellus** [cnr-isti-vclab/PyMeshLab#104]
I am getting crashes of both  select_by_face_quality() select_by_vertex_quality()  sometimes, but not always. I have the parameters set low (minq 0, maxq .1), but I don't think this has anything to do with it. I suspect what is happening is that it is failing when a zero value is returned? Not sure how to provide a minimal example, as it does not happen every time. I'll spend some time seeing if I can figure this out, but has anyone else encountered it? I haven't had this happen in GUI Meshlab.

**Comment by Cervidellus** [comment]
OK, here is the minimal example. If I load any mesh that has no zero area faces, and then color the faces with meshset.per_face_quality_according_to_triangle_shape_and_aspect_ratio(metric = 3), selecting via meshset.select_by_face_quality(minq = 0, maxq = 0) returns the following:
`C:\ProgramData\Anaconda3\envs\meshparty\lib\site-packages\pymeshlab\__init__.py in foo(self, **kwargs)
     20 def bind_function(name):
     21     def foo(self, **kwargs): # Have to add self since this will become a method
---> 22         dict = self.apply_filter(name, **kwargs)
     23         if (bool(dict)): # return the dictionary only if it is not empty
     24             return dict

PyMeshLabException: Parameter minq: float value 0 out of bounds (min: 0.000366211; max: 0.128194).`

In the c++ version it doesn't crash, just doesn't select anything.

**Comment by alemuntoni** [comment]
Hi, actually the issue is related to the `minq` and `maxq` parameters. 
The filter `select_by_face_quality` takes two parameters that are "bounded", and the bounds depends on the input shape. In your case, you get exactly the issue:
```
Parameter minq: float value 0 out of bounds (min: 0.000366211; max: 0.128194).`
```
Therefore, you need to give to the `minq` parameter a value between the two bounds.

In MeshLab, the GUI does not allow to go out of bounds.

**Comment by redocrepus** [comment]
> Hi, actually the issue is related to the `minq` and `maxq` parameters. The filter `select_by_face_quality` takes two parameters that are "bounded", and the bounds depend on the input shape. In your case, you get exactly the issue:
> 
> ```
> Parameter minq: float value 0 out of bounds (min: 0.000366211; max: 0.128194).`
> ```
> 
> Therefore, you need to give to the `minq` parameter a value between the two bounds.
> 
> In MeshLab, the GUI does not allow to go out of bounds.

How can I know what the bounds are before applying the filter?

**Comment by redocrepus** [comment]
Got it:
	out_dict = ms.apply_filter('per_vertex_quality_stat')
	ms.apply_filter('select_by_vertex_quality', minq=out_dict['min'], maxq=1.0)
