### ISSUE TITLE
[feature request] making availible Texture map defragmentation filter

### ISSUE THREAD

**Issue by jambus1986** [cnr-isti-vclab/PyMeshLab#110]
Hi, Texture map defragmentation is such a great tool,
can you make it availible as a filter in python?

greetings..

**Comment by alemuntoni** [comment]
Hi, yes, of course it will be available also in pymeshlab!
It actually already is, and you can try it just installing the wheel of the last nightly build of pymeshlab (Tab Actions -> Select Linux, MacOS or Windows -> click on the last run ->  download the package "python_whl_*" depending on your python version, extract and install the whl file with  `pip install pymeshlab*.whl`).
The filter has still some issues (it does not work on macos due to opengl crashes...)

**Comment by jambus1986** [comment]
i tried it...following message appears: 


ms.texture_map_defragmentation(matchingthreshold=5, boundarytolerance=0.02, distortiontolerance=3, globaldistortiontolerance=0.5, offsetfactor=50)
  File "C:\Users\Kamprad\AppData\Roaming\Python\Python39\site-packages\pymeshlab\__init__.py", line 27, in foo
    dict = self.apply_filter(name, **kwargs)
pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: texture_map_defragmentation
Details: GLEW initialization failed: Missing GL version

**Comment by alemuntoni** [comment]
You're right, I'm sorry :(
I'm still getting some issues on having the plugin working in pymeshlab... I'll update here whenever it will work.

**Comment by alemuntoni** [comment]
@jambus1986 all the main issues should be fixed and the texture defragmentation plugin should work now in the last nightly.
If you want to try it, you can follow these instructions to download the last nightly: https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-intall-the-last-nightly

There is still the issue of the position of the newly generated texture, which will be placed in the same directory of the input mesh. I hope to solve this for the next version of pymeshlab

**Comment by jambus1986** [comment]
Hi, i tried it, and it seems to work now, but if i try to safe the meshset, following error occours:


py-file:
   ms.texture_map_defragmentation(matchingthreshold =2, boundarytolerance =0.2, distortiontolerance =0.5, globaldistortiontolerance =0.025, offsetfactor =5, timelimit =0)
   ms.   ms.save_current_mesh("outdefrag.obj")


---->


Traceback (most recent call last):
  File "D:\tmp\meshlabScript2.py", line 126, in <module>
    main(sys.argv[1:])
  File "D:\meshlabScript2.py", line 121, in main
    ms.   ms.save_current_mesh("outdefrag.obj")
AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'ms'

**Comment by alemuntoni** [comment]
> ms. ms.save_current_mesh("outdefrag.obj")
> ---->
> **ms. ms.save_current_mesh("outdefrag.obj")**
> AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'ms'

I suggest to read at least the error message before posting the error here...
Should be
```
ms.save_current_mesh("outdefrag.obj")
```

**Comment by jambus1986** [comment]
i read it at least 20 times before and i fool didnt see it :) :) :)
thx
now it works fine
