### ISSUE TITLE
What version of Python is required?

### ISSUE THREAD

**Issue by CarpeCimex** [cnr-isti-vclab/PyMeshLab#115]
I have Python v3.7.3 and when I run 'pip install pymeshlab' I get:

ERROR: Could not find a version that satisfies the requirement pymeshlab (from versions: none)
ERROR: No matching distribution found for pymeshlab

I think this is due to a Python version mismatch, but I don't see Python version requirements in the pymeshlab documentation.  What version is required?  And I recommend you put that on https://pymeshlab.readthedocs.io/en/latest/installation.html .

EDIT: this is due to using a 32-bit version of Python.

**Comment by alemuntoni** [comment]
Yes, pymeshlab supports python >= 3.6 64bit. Meshlab (and therefore pymeshlab) cannot be built on 32bit.
I'll add this info in the documentation.
