### ISSUE TITLE
Shape Diameter Function -> Conditional Vertex Selection, Crash

### ISSUE THREAD

**Issue by Crofttime** [cnr-isti-vclab/PyMeshLab#121]
I'm having a weird problem where the script apparently crashes at "conditional_vertex_selection" without specifying the error, if I comment it out it seems to work:
```
                        ms = pymeshlab.MeshSet()
                        ms.load_new_mesh('mesh1.ply')
                        ms.load_new_mesh('mesh2.ply')
                        ms.flatten_visible_layers()
                        ms.shape_diameter_function()
                        ms.conditional_vertex_selection(condselect='(q<0.05)')
                        ms.select_faces_from_vertices(inclusive=False)
                        ms.invert_selection(invfaces=True,invverts=True)
                        ms.delete_selected_faces_and_vertices()
                        ms.save_current_mesh('out.ply')
```

**Comment by alemuntoni** [comment]
Hi, could you please share the two meshes on which pymeshlab crashes? Thanks!

**Comment by Crofttime** [comment]
[meshes.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/6869370/meshes.zip)
Here they are... thanks for your help and all the great work you do with this project!

**Comment by Crofttime** [comment]
A work around seems to be to save the mesh after the shape diameter function, then reload it and run the conditional_vertex_selection etc.

**Comment by alemuntoni** [comment]
Were you running the 2021.7 version of pymeshlab? Which platform are you using?
I am not able to reproduce this crash, on linux with 2021.7.

**Comment by Crofttime** [comment]
I am running 2021.7 on Windows 10

**Comment by alemuntoni** [comment]
Solved in the last commit!
