### ISSUE TITLE
Error installing via pip on windows 10 (python 3.8.1)

### ISSUE THREAD

**Issue by EndemolUK** [cnr-isti-vclab/PyMeshLab#122]
Hi Guys

Really want to try pymeshlab - I think it could be really useful for me but when I try to install via pip I get this:

```
ERROR: Could not find a version that satisfies the requirement pymeshlab (from versions: none)
ERROR: No matching distribution found for pymeshlab
```

I've tried downloading the whl for windows and python 3.8 from pip and running an install from that and I get similar issues.

I'm now downloading tools to try and build from source but visual studio on my machine isn't playing ball (at the moment, which is doubly frustrating).

If there is anything you can to improve (fix) the windows build for pip it'd be appreciated (I guess I'm not the only person with a problem here :) )

**Comment by EndemolUK** [comment]
Actually I've figured out the issue here - I'm on 64 bit windows but happened to have the 32 bit version of python 3.8 installed, as there's not a win32 build of this on pip, pip couldn't match it.

I don't know if a win32 build is possible for meshlab but it might be worth adding to the build options if so, just to avoid people asking this kind of question :)

**Comment by alemuntoni** [comment]
Hi, 
In the documentation we specify that a 64bit system is required: https://pymeshlab.readthedocs.io/en/latest/installation.html

Meshlab has been compiled for almost 10 years in 64-bit only, and I doubt that it could be compiled in 32bit easily.
We have limited resources (I am the only one maintaining meshlab and pymeshlab), and I can't maintain also a 32bit version which, in my honest opinion, it's not worth to be maintained in 2021.

If you, or anyone else, has free slots to make this available, pull requests are always welcome.

**Comment by EndemolUK** [comment]
Yes, as I say it was my issue - I'm not sure why I had a 32-bit python installed to be honest (everything else I use is 64-bit)... and I agree that if a win32 build isn't just a flag in a config basically, then it's probabaly not worth doing.

It wasn't clear that this was my problem initially though (more pip's fault than anything here) but for that reason it might be worth an extra line in the docs to mention something like this just in case other people have this problem, and give up thinking it just doesn't work.

Even something like "If it doesn't install via pip first time double check you ARE actually running 64-bit python"

Up to you if you include something like that or not of course but it might stop similar stupid questions occurring from time to time :)

**Comment by EndemolUK** [comment]
Also thanks for the work on this - since installing it, it looks like it's going to be super helpful and if I can contribute something to it in future I will

**Comment by alemuntoni** [comment]
You're right, I'll add a disclaimer in the install page of the documentation. Thanks!!
