### ISSUE TITLE
transfer_vertex_attributes_to_texture_1_or_2_meshes crashes with generated flat plane UVs

### ISSUE THREAD

**Issue by Crofttime** [cnr-isti-vclab/PyMeshLab#124]
I have a mesh with flat plane UVs generated using "ms.parametrization_flat_plane(aspectratio=True)".  When I try to transfer vertex colors to a texture using "transfer_vertex_attributes_to_texture_1_or_2_meshes" it crashes.  It also crashes when trying to replicate it in Meshlab 2021.07, however it does not crash in either Meshlab v1.3.4BETA or Meshlab 2016.12.  I have the same result with UVs generated using Trivial Per Triangle.   However, if I generate UVs using "[xatlas](https://github.com/mworchel/xatlas-python)" it works (file is also attached).

```
ms = pymeshlab.MeshSet()
ms.load_new_mesh('ortho.stl',unify_vertices=False)
ms.remove_duplicate_vertices()
ms.parametrization_flat_plane(aspectratio=True)
ms.save_current_mesh('ortho_uv.obj')

ms = pymeshlab.MeshSet()
ms.load_new_mesh('ortho_uv.obj') #Doesn't Work
#ms.load_new_mesh('ortho_uv_atlas.obj') #Works
ms.load_new_mesh('color.ply')
ms.transfer_vertex_attributes_to_texture_1_or_2_meshes(sourcemesh=1,targetmesh=0)
ms.change_the_current_layer(layer=0)
ms.save_current_mesh('output.obj')
```

[uvissue.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/6900483/uvissue.zip)

Again, thank you for all your hard work on this incredibly awesome project!

**Comment by alemuntoni** [comment]
Hi,
thanks for reporting!

This issue should be already solved in meshlab (see https://github.com/cnr-isti-vclab/meshlab/issues/975). Could you please try the [last meshlab nightly](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) and check if still crashes? 
I tried on my machine and it didn't crash. 
The fix will then reflect also in the next version of pymeshlab.

**Comment by Crofttime** [comment]
Just tried it on the nightly meshlab build - windows/double/portable - and it works!

**Comment by alemuntoni** [comment]
Great! Therefore it is solved also in pymeshlab!
You can try also the [last nightly of pymeshlab](https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-intall-the-last-nightly), if you want!

**Comment by Crofttime** [comment]
Awesome!  I'd like to try it out - Is there a tutorial for trying the nightly build of pymeshlab?

**Comment by alemuntoni** [comment]
Yes, I also linked it in my last reply: https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-intall-the-last-nightly
