### ISSUE TITLE
pmeshlab.MeshSet.load_new_mesh() does not support having a path as a file name anymore

### ISSUE THREAD

**Issue by Max----** [cnr-isti-vclab/PyMeshLab#126]
`for folder in foldersOfInterest:`
    `ms = pymeshlab.MeshSet()`
    `ms.load_new_mesh(folder + '/' + folder +'.obj')`
    `... more processing`

This used to work, but I now get a systematic error (on toy example):

`ms.load_new_mesh(folderOfInterest + '/' + 'Tile4.obj')`
`pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: Data/Tile4.obj`
`Error encountered while loading file:`
`"Data/Tile4.obj"`

`Error details: File does not exist`

Note that the error printed when the file actually doesn't exist is:

`ms.load_new_mesh(folderOfInterest + '/' + 'Tile4.obj')`
`pymeshlab.pmeshlab.PyMeshLabException: File does not exists: Data/Tile4.obj`

It used to work with previous library versions but somehow errors out now.

**Comment by alemuntoni** [comment]
That's weird. We actually have lot of tests using path + file as filename, and they are all working on all platforms. e.g.: https://github.com/cnr-isti-vclab/PyMeshLab/blob/399d15e5adeb6fccedd64a72b0ce2e579b73b919/pymeshlab/tests/example_load_mesh.py#L15

Which version of pymeshlab and which platform are you using?

**Comment by alemuntoni** [comment]
Ok, I did some tests and I can confirm that relative paths do not work anymore on 2021.07 version.
I'll investigate and solve this issue, thanks for reporting!
In the meantime, absolute paths and in-place files (e.g. `ms.load_new_mesh('cube.obj')`) work as expected, therefore for this version I suggest to switch to absolute paths. Sorry for that!

**Comment by alemuntoni** [comment]
Solved in the last commit, the fix will be available in the next pymeshlab version!

**Comment by Max----** [comment]
Hey, thanks for the fix :) Doing superb work on a public software, a big thank you from the 3D community
