### ISSUE TITLE
save_current_mesh raised error with "IndexError: map::at" after doing flatten_sisiable_layers()

### ISSUE THREAD

**Issue by caopengbo** [cnr-isti-vclab/PyMeshLab#129]
I try to merge two obj files to one using flatten_sisiable_layers() method. I built a MeshSet instance "ms" and loaded two meshes with ms.load_new_mesh(). Then I applied flatten_sisiable_layers() and merge_close_vertices() on the instance "ms".

When I tried to save the output mesh using ms.save_current_mesh(file_name="./**.obj", save_textures=True), the error "IndexError: map::at" raised. However the output obj is correctly saved.

I am not sure if there is any problem with the flatten function or I used that in a wrong way, cause there is few information regarding that. Sorry about that I can't write the orginal code for some reasons.

Looking forward to any kind reply, Thanks.

**Comment by alemuntoni** [comment]
Hi, 
I cannot replicate the issue. Could you please share at least a dummy portion of code that replicates the issue, with some dummy input meshes?
Also:
- which OS are you using?
- have you installed the last version of pymeshlab (2021.7)?

**Comment by Crofttime** [comment]
I just tried it and had the same problem - on Windows 10, also crashes, but successfully exports the flattened file when using Meshlab 2021.07.  Error I get is:

    ms.save_current_mesh('test2.ply')
IndexError: invalid map<K, T> key

``ms = pymeshlab.MeshSet()
ms.load_new_mesh('chunk_-60_-30_small.obj')
ms.load_new_mesh('chunk_-60_-30_complex.obj')
ms.load_new_mesh('chunk_-60_-30_ortho.obj')

ms.flatten_visible_layers(mergevertices=False)

ms.save_current_mesh('test2.ply')``

[testfiles.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/7013906/testfiles.zip)

**Comment by alemuntoni** [comment]
Solved in the last commit. The fix will be available in the next pymeshlab version
