### ISSUE TITLE
pymeshlab and embedded Python: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by ChrisDean** [cnr-isti-vclab/PyMeshLab#132]
Somewhat similar to Issue #23

I seem to have a problem loading pymeshlab from an embedded python install on windows. 

A standard python install on windows works fine (both are 64 bit 3.7.x installs).

I have the issue:
```
DLL load failed: The specified procedure could not be found.
```

Having looked at a couple of tracebacks it seems to be finding and loading the pmeshlab.pyd (i.e. the pmeshlab module loads) but then it seems to fail (looking for? referencing? loading?) a particular procedure in that pyd...

I'm wondering if this is some path referencing issue or similar within the pmeshlab.pyd itself which maybe works fine when dealing with the system PATH/PYTHONPATH but not when an embedded install calls it? 

I fully admit I'm guessing here but I'm running out of things to try to make this work when called from an embedded python install. 

Any thoughts?

Thanks

Chris

**Comment by alemuntoni** [comment]
Hi,

could be the same issue of #47. It could be that the embedded install does not like system PATH or PYTHONPATH, but I don't know why and if there is a common way to solve this...

**Comment by misan** [comment]
Have you installed Python from the Windows store? Just curious if that could be the culprit.

**Comment by EndemolUK** [comment]
Hi Guys
No I have used the embedded version of 3.7.x (specifically 3.7.4 in this test) from the python website.
It does seem to find and load the module, from running a trace on it I think it's a call within the module that's failing to be found causing this procedure not found error.
Same issue occurs from pre-built wheels and manual build.
Like everyone I don't have lot of time to look at this but am trying different things when I can, and if I find an answer I'll provide feedback.
It feels like a "simple" (path/module/include) referencing thing somewhere... 
It works fine with the msi installed version of python just not the embedded.

**Comment by EndemolUK** [comment]
I should add 
Yes #47 does seem to be the same problem (same symptom) and I forgot to mention in my own debugging it did seem to be something around the Qt libs that might have been the issue.
Are the Qt includes required for the python build? If not though I appreciate it might be too much of a departure from your core MeshLab build to exclude them for python, it might be an interesting test to see if this is the issue...

**Comment by EndemolUK** [comment]
And sorry have just read lower down on #47 and I think you've already answered the point in my last reply there - they are needed in part.
I will continue to play with this myself and will feedback if I find any solution that works. I'll also keep an eye on this thread and #47 for any other progress.

**Comment by alemuntoni** [comment]
Yes @EndemolUK, Qt is a strong dependency of meshlab and pymeshlab. All the meshlab plugins are actually Qt plugins.
A similar issue (which is experienced on macos) could be #133. 
Having two Qt directories inside a conda env seems to break everything, and could be the same in an embedded env.. 
Does your embedded environment have another Qt installation somewhere?
