### ISSUE TITLE
implicit_surface does not support x**2

### ISSUE THREAD

**Issue by rellevarta** [cnr-isti-vclab/PyMeshLab#134]
Hi guys, 
I found the  implicit_surface is a useful tool for generating complex surfaces like minimal surface gyroid, but there is a problem, pymeshlab only accept x*x instead of x**2, while python supports both. So, how to make pymeshlab accept expressions python supports?

**Comment by cignoni** [comment]
meshlab for implicit_surface evaluation uses muparser, a c++ fast math expression parser.

 https://beltoforion.de/en/muparser/features.php#idDef2

muparser adopts the `^`  instead of  `**` for power elevation. 
As a workaround just search and replace `**` with  `^` in your expressions
