### ISSUE TITLE
ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'

### ISSUE THREAD

**Issue by eduvillasr** [cnr-isti-vclab/PyMeshLab#136]
I have been looking into an error:

```
from .pmeshlab import *
ImportError: DLL load failed while importing pmeshlab: The specified procedure could not be found.
```
and uninstalled and reinstalled pymeshlab and am now getting the following error:
```
  File "C:\Users\edujo\anaconda3\lib\site-packages\pymeshlab\__init__.py", line 12, in <module>
    from .pmeshlab import *

ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'
```

The module is not importing and all my other modules are working. This problem goes away on its own every now and then but comes back.

**Comment by jcraz** [comment]
I have met the same error and I don't know how to solve it. Could you give me some help?
