### ISSUE TITLE
I cannot find bounding box min or max

### ISSUE THREAD

**Issue by misan** [cnr-isti-vclab/PyMeshLab#138]
While I can get these using Compute Geometric measures in Meshlab, I only get a BoundingBox object in PyMeshLab which only provides dim_x, dim_y, dim_z, and diagonal values, but not the min and max coordinates of the bounding box.

Maybe this is done by design. And if that is the case I could still obtain these values going through the mesh vertices, but I report this just in case.

**Comment by misan** [comment]
This will do for me:

```
def bbox(mesh):
    mi = np.zeros(3)
    ma = np.zeros(3)
    v = mesh.vertex_matrix()
    for i in range(3):
        mi[i] = np.min(v[:,i:i+1])
        ma[i] = np.max(v[:,i:i+1])
    return tuple(zip(mi, ma))
```

**Comment by alemuntoni** [comment]
It will appear in the next version of pymeshlab!
