### ISSUE TITLE
face_matrix of quad mesh still is a nx3 array instead of nx4?

### ISSUE THREAD

**Issue by rellevarta** [cnr-isti-vclab/PyMeshLab#139]
while using tri_to_quad_by_4_8_subdivision(), why is the face_matrix of quad mesh still is a nx3 matrix :

import pymeshlab
ms = pymeshlab.MeshSet()
ms.load_new_mesh('tri_mesh')
ms.remeshing_isotropic_explicit_remeshing()
ms.tri_to_quad_by_4_8_subdivision()
m = ms.current_mesh()
f = m.face_matrix()

print(f)
print(f.shape)

**it gives:**
[[    0 27389     3]
 [27390    20  5275]
 [ 9491    17  5274]
 ...
 [ 3953  3759 27932]
 [ 8885  3851 27933]
 [ 8962  5215 27934]]
(54786, 3)

**Comment by alemuntoni** [comment]
MeshLab stores internally only triangle meshes.
Also if they are visualized as quad or polygonal meshes, they are triangle meshes with [faux edges](https://stackoverflow.com/questions/59392193/what-are-the-faux-edges-on-meshlab).
Right now a way to get this info in pymeshlab is missing, unfortunately. The return type of the `face_matrix()` method is a N by 3 matrix, always.
I'll add a method to the mesh class that will allow to extract the indices of the polygons in future versions of pymeshlab.

**Comment by rellevarta** [comment]
> MeshLab stores internally only triangle meshes.
> Also if they are visualized as quad or polygonal meshes, they are triangle meshes with [faux edges](https://stackoverflow.com/questions/59392193/what-are-the-faux-edges-on-meshlab).
> Right now a way to get this info in pymeshlab is missing, unfortunately. The return type of the `face_matrix()` method is a N by 3 matrix, always.
> I'll add a method to the mesh class that will allow to extract the indices of the polygons in future versions of pymeshlab.

Thanks for your efforts. Meanwhile, I saved the mesh as '.obj' file first, then read the point and face matrix info, it works but is not very convenient.

**Comment by rellevarta** [comment]
> MeshLab stores internally only triangle meshes.
> Also if they are visualized as quad or polygonal meshes, they are triangle meshes with [faux edges](https://stackoverflow.com/questions/59392193/what-are-the-faux-edges-on-meshlab).
> Right now a way to get this info in pymeshlab is missing, unfortunately. The return type of the `face_matrix()` method is a N by 3 matrix, always.
> I'll add a method to the mesh class that will allow to extract the indices of the polygons in future versions of pymeshlab.

Thanks for your efforts. Meanwhile, I saved the mesh as '.obj' file first, then read the point and face matrix info, it works but not very convenient.

**Comment by alemuntoni** [comment]
Yes, that's another way. Both obj and off file format support polygonal meshes in meshlab.
Hope this workaround will be not necessary soon :)

**Comment by alemuntoni** [comment]
Added this feature in the last commit. Will be available in the next version of PyMeshLab!
