### ISSUE TITLE
DLL not installing along with pymeshlab

### ISSUE THREAD

**Issue by eduvillasr** [cnr-isti-vclab/PyMeshLab#140]
I have been dealing with this problem for a while and no solution has worked so far. I am getting the following error

```
    from .pmeshlab import *

ImportError: DLL load failed while importing pmeshlab: The specified procedure could not be found.
```

Under the directory there is no pmeshlab.dll file, just the following files:
https://imgur.com/a/QvEuP5z

I don't think the .dll file is installing and don't know why.

**Comment by alemuntoni** [comment]
Duplicate of #47 
Please refer to that issue for future updates on this problem.
