### ISSUE TITLE
Visualization of triangles when we use a filter 'select_problematic_faces'

### ISSUE THREAD

**Issue by SpyridoulaZagkou4** [cnr-isti-vclab/PyMeshLab#142]
Hello,

I use pymeshlab library for my project. I have some questions.

1)I want to apply the filter ‘select_problematic_faces’, for visualizing with different color the problematic faces. When I use Meshlab the selected triangles are shown with different(red) color. But when I run it as a script with pymeshlab there are not colorized. How can I colorize them?
2)Is there a way to return the number of selected faces from filter ‘select_problematic_faces’ (with python script)
3)Is there a script to apply the Meshlab process Render>> Show Normal?
4)In my project I want to correct non manifold surfaces. When I use filter ‘select_non_manifold_edges’ , it doesn’t return any selected face. When I use filter ‘repair_non_manifold_vertices_by_removing_faces’ and ‘repair_non_manifold_vertices_by_splitting faces’ applies changes to the mesh. What is the exact operation of these filters? Is there another way to visualize non_manifold edges?
 
Thank you in advance,

Spyridoula Zagkou

**Comment by alemuntoni** [comment]
1) not, there is not way right now. I'll add in the future some methods in the [Mesh class](https://pymeshlab.readthedocs.io/en/latest/classes/mesh.html) to get an array of booleans that tells if the ith vertex/face is selected;
2) there is the possibility to know the number of selected vertices and faces of the current mesh:
```
m = ms.current_mesh()
nf = m.selected_face_number()
nv = m.selected_vertex_number()
```  
3) Nope, render methods cannot be executed in pymeshlab. You can get a matrix containing the normals using the vertex[face]_normal_matrix() method of the Mesh class;
4) if the select_non_manifold_edges filter does not select nothing, it means that there are no manifold edges; for further details on what each filter does, please refer to the [documentation](https://pymeshlab.readthedocs.io/en/latest/filter_list.html)

Keeping this issue open as a reminder for the implementation of the additional methods of the Mesh class.

**Comment by SpyridoulaZagkou4** [comment]
@alemuntoni Thank you for yor response!
Is it the new process available? I installed again pymeshlab but the added matrix 'face_selection_array' is not recognizable.

**Comment by alemuntoni** [comment]
@SpyridoulaZagkou4 no, it will be available in the next release. I still don't exactly when it will be out..  by the end of October I think
