### ISSUE TITLE
How to get the curvature results using discrete_curvatures

### ISSUE THREAD

**Issue by morgan-bc** [cnr-isti-vclab/PyMeshLab#143]
I use `MeshSet.discrete_curvatures(curvaturetype =1)` to compute gaussian curvature. How to get the results of the computation?

**Comment by alemuntoni** [comment]
It is not possible right now. I'll add this feature in future versions of pymeshlab.

**Comment by alemuntoni** [comment]
Actually I was partially wrong: if you need only the scalar value, the filter stores it into the quality; therefore, you can get it by calling the [`vertex_quality_array`](https://pymeshlab.readthedocs.io/en/latest/classes/mesh.html#pmeshlab.Mesh.vertex_quality_array) function of the Mesh class. Curvature direction is still missing, and will be added in future versions.

**Comment by morgan-bc** [comment]
There may be some problems with  the function `vertex_quality_array `.
The results obtained using `vertex_quality_array ` are different to those computed directly by meshlab. For the same mesh (download from [google drive](https://drive.google.com/file/d/11KIuugUt74MbOfqkDif_oBIaV3yiTwEu/view?usp=sharing)), the curvature results using methlab are
```
Computed Gaussian Curvature
Curvature Range: -4.421292 6.333511 (Used 90 percentile -0.424441 0.555837)
Computed Mean Curvature
Curvature Range: -31.262203 5.893018 (Used 90 percentile -0.939828 0.616976) 
```
the results using pymeshlab and `vertex_quality_array `  are
```
Gaussian Curvature range: -62.926323581822125 121.3203166496188
Gaussian Curvature range 90 percent: -26.454880156636023 -4.748399149803555
Mean Curvature range: -31.262201196368366 5.8930180411155835
Mean Curvature range 90 percent: -9.125196044811734 -3.550476896866143
```

The codes using pymeshlab are

```python
mesh_file = 'face.ply'
ms = pymeshlab.MeshSet()
ms.load_new_mesh(mesh_file)
ms.discrete_curvatures(curvaturetype=1)
mesh = ms.current_mesh()
qarr = mesh.vertex_quality_array()
print('Gaussian Curvature range:', qarr.min(), qarr.max())
q = np.percentile(qarr, [0.1, 0.9])
print('Gaussian Curvature range 90 percent:', q[0], q[1])

ms.discrete_curvatures(curvaturetype=0)
qarr = mesh.vertex_quality_array()
print('Mean Curvature range:', qarr.min(), qarr.max())
q = np.percentile(qarr, [0.1, 0.9])
print('Mean Curvature range 90 percent:', q[0], q[1])
```

**Comment by keblicuey** [comment]
Thanks for your impressive work. I wonder where to find vertex_quality_array in pymeshlab2023.12
