### ISSUE TITLE
Not possible to initialize mesh with vertex colors?

### ISSUE THREAD

**Issue by sergiobdrl** [cnr-isti-vclab/PyMeshLab#144]
Hi,

I have succesfully loaded and played around with a numpy generated mesh using points and normals using attributes `vertex_matrix` and `v_normals_matrix`, as suggested by the [documentation](https://pymeshlab.readthedocs.io/en/latest/classes/mesh.html). How to set per-vertex colors in this constructor? It seems possible to **get** the vertex color matrix, but I have not found how to set it.

Any help would be greatly appreciated

**Comment by alemuntoni** [comment]
You're right, there is no way to initialize a mesh with per-vertex and per-face colors. I'll add this feature in the next pymeshlab release.

**Comment by sergiobdrl** [comment]
Thank you for the amazingly quick answer!
In the meantime I guess there is also no way to load (set) per-vertex color after initialization, right?

**Comment by alemuntoni** [comment]
I guess you could do some hack, like
```
ms.per_vertex_color_function(z='255') # initialize v colors to white

for curr_v in range(ms.current_mesh().vertex_number())
    ms.per_vertex_color_function(x='(' + str(curr_v) + ' == vi) * ' + str(some_color_r) + ' + (' + str(curr_v) + ' != vi) * r')
```

The idea is to apply a function that sets `some_color_r` just to `curr_v` vertex. The same goes for green component (`y`) and blue (`z`). 

It is a very horrible and inefficient hack, and I'm not sure if there is a better way... But it should work!

**Comment by sergiobdrl** [comment]
Got it. In the meantime I'll stick with exporting and loading as text (which is what I was trying to avoid in the first place). Look forward to the next release.
