### ISSUE TITLE
Conditional vertex selection crashes

### ISSUE THREAD

**Issue by Freakaz0id** [cnr-isti-vclab/PyMeshLab#147]
I applied the conditional vertex selection filter after computing the shape diameter function on a meshset:

```python
ms.shape_diameter_function(
    onprimitive='On vertices',
    numberrays = 128,
    depthtexturesize = 512,
    peelingiteration = 10,
    peelingtolerance = 1e-07,
    coneangle = 120
    removefalse = True,
    removeoutliers = False
)

ms.apply_filter('conditional_vertex_selection', condselect='(q > 0.01) && (q < 1.5)')
```

The program exits without raising an error.

- Works in MeshLab (Windows)
- Tried 3 different meshes
- 'conditional_face_selection' with SDF on faces works fine

**Comment by alemuntoni** [comment]
This issue has been already solved in previous commits, and the fix will be available in the next pymeshlab release.
In the meantime if you want you can try the last [nightly version](https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-intall-the-last-nightly).

**Comment by Freakaz0id** [comment]
Alright, I have not seen, that is has been solved. Thanks a lot!
Great repo by the way. Makes working with Meshlab much easier.
