### ISSUE TITLE
normalize_vertex_function not working

### ISSUE THREAD

**Issue by PatakiMarton** [cnr-isti-vclab/PyMeshLab#148]
The ""normalize_vertex_normals" filter is not working, I tried ms.apply_filter("normalize_vertex_normals") and ms.normalize_vertex_normals() aswell.

`def main():

    ms = pms.MeshSet()
    path = r"example.ply"
    ms.load_new_mesh(path)

    # ms.compute_normals_for_point_sets(k=30, smoothiter=10, flipflag=True)
    # ms.normalize_vertex_normals()
    # ms.surface_reconstruction_screened_poisson()
    #
    # ms.taubin_smooth(lambda_=0.8, stepsmoothnum=80)
    # ms.normalize_vertex_normals()

    ms.apply_filter('compute_normals_for_point_sets', k=30, smoothiter=10, flipflag=True)
    ms.apply_filter("surface_reconstruction_screened_poisson")
    ms.apply_filter("taubin_smooth", lambda_=0.8, stepsmoothnum=80)
    # ms.apply_filter("normalize_vertex_normals")  # does not work in the pymeshlab package
    ms.save_current_mesh("reconstructed_norm.ply")`

**Comment by alemuntoni** [comment]
How do you check if the filter works?

When you save a ply, vertex normals are not saved by default (https://pymeshlab.readthedocs.io/en/latest/io_format_list.html).

**Comment by PatakiMarton** [comment]
I missed that, thank you.
