### ISSUE TITLE
Release the GIL

### ISSUE THREAD

**Issue by EpicWink** [cnr-isti-vclab/PyMeshLab#162]
Release CPython's global interpreter lock (GIL) when running pure C/C++ code.

When we're in non-Python territory (ie after converting all Python types to C, and running MeshLab library code), we don't need to hold the GIL. Releasing this will allow other threads to run MeshLab on other independent objects at the same time (assuming MeshLab is thread-safe as a library). Care will need to be taken that we have no global state (eg static/global variables etc), nor any state shared between threads (unless the user explicitly ignores the "objects are not thread-safe" warning I recommend you also include in the docs).

See: https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil

**Comment by alemuntoni** [comment]
I'm looking on this but I'm not very familiar with python multithreading, so I'll ask for some confirmation.
As far as I know, there should be no global or static variables in filters internal code (and if there are, they should be removed).
The only "global state" concerns the "plugin list", that is global in a pymeshlab session, but it is loaded only while importing pymeshlab and it is not modified when applying filters.

From what I understand, the GIL should be released on long-running C++ code, that in pymeshlab occurs when applying filters and when loading/saving meshes (but I'm not sure if releasing it while loading/saving files makes sense at all).
So, according to the [pybind docs](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil), I think that we just need to add the argument `py::call_guard<py::gil_scoped_release>()` [here in the apply_filter binding](https://github.com/cnr-isti-vclab/PyMeshLab/blob/d9edc703130cb88494b7170137c8807afd5f5a06/src/pymeshlab/bindings/pymeshset.cpp#L115-L116). Does this make sense?

Of course a MeshSet object is not thread safe, but multiple MeshSet objects could be used in parallel without problems, I think.

**Comment by EpicWink** [comment]
> I'm looking on this but I'm not very familiar with python multithreading

It comes down to: standard multithreading, but there's a single process-global lock which must be held for Python operations (assignment, function calls, etc), which is the mechanism which prevents parallelism. Extension (C-based) libraries typically release the GIL for file/network IO and Python-unrelated computation to re-enable parallelism in multi-threading.

> The only "global state" concerns the "plugin list"

Import-time global state is generally fine, you can always explicitly acquire the GIL if that global state is modified at run-time in the future.

> From what I understand, the GIL should be released on long-running C++ code

As long as that C++ doesn't interact with Python objects (or allocates/de-allocates Python-managed memory, which I don't know what looks like in `pybind`)

> I think that we just need to add the argument `py::call_guard<py::gil_scoped_release>()` [here in the apply_filter binding](https://github.com/cnr-isti-vclab/PyMeshLab/blob/d9edc703130cb88494b7170137c8807afd5f5a06/src/pymeshlab/bindings/pymeshset.cpp#L115-L116). Does this make sense?

I think so: again, I'm not too familiar with `pybind`, so try it and see I guess.

> Of course a MeshSet object is not thread safe, but multiple MeshSet objects could be used in parallel without problems, I think.

That's fine then, as long as `PyMeshLab`'s documentation mentions this.
