### ISSUE TITLE
Mesh simplification with preservetopology=True not simplifying

### ISSUE THREAD

**Issue by cajoek** [cnr-isti-vclab/PyMeshLab#165]
Hi I'm trying to simplify some meshes without introducing holes in them.
I use the following code:
```
my_mesh_set.simplification_quadric_edge_collapse_decimation(targetfacenum=22528, preservenormal=True, preservetopology=True)
```
But it only decimates a very small number of faces. Here are the number of faces before and after simplification.
| # Faces before        |  # Faces after          | Reduction |
|:-------------:|:-------------:|:-----:|
| 279672 | 262983 | 5.967 % |
| 146176 | 145740 | 0.298 % |
| 45180 | 45178 | 0.004 % |
| 96500 | 96492 | 0.008 % |
| 169826 | 169806 | 0.011 % |
| 24454 | 24396 | 0.237 % |
| 40452 | 39946 | 1.250 % |
| 50010 | 49801 | 0.417 % |

Only a very small number of faces get decimated and none of them are below the desired number of faces.
If I remove the `preservetopology` constraint the meshes get adequately simplified but it instead introduces holes (missing triangles) in them.

Is this an error or am I misunderstanding somthing?
Thanks!

**Comment by jmespadero** [comment]
Hi,

One posible reason is that you have a "triangle soup mesh", where almost every vertex is duplicated in each triangle. If this is the case, every edge is a boundary of the mesh and it is not possible to reduce the mesh without changing the topology.
One solution is to call the "Remove Duplicate vertex" filter before of the simplification.

```py
my_mesh_set.remove_duplicate_vertices()
```

It is hard to say what is hapenning without seeing your meshes. Is it possible to share here one mesh with that problem? or at least one screenshot of meshlab after executing the "select border" filter.

**Comment by cajoek** [comment]
Hi @jmespadero unfortunately I don't think that is the problem. All meshes i use come from the ShapeNetCore dataset https://shapenet.org/. I switched to using simplify_quadric_decimation() from open3d and then it worked.

**Comment by jmespadero** [comment]
Could you share the link to the mesh? I have been using this with no problem until today.

```python
ms.apply_filter('simplification_quadric_edge_collapse_decimation', targetfacenum=numFaces, preservenormal=True, preservetopology=True)
```

**Comment by cajoek** [comment]
Unfortunate I don't have the code any more and the dataset license doesn't allow me to share it but if you want to you can ask to get access to it on the website. One of the meshes I was experimenting with and having this problem has the path `ShapeNetCore.v2/02773838/4e4fcfffec161ecaed13f430b2941481/models/model_normalized.obj` in the dataset
