### ISSUE TITLE
Multiple filters that should save a texture image are not doing so.

### ISSUE THREAD

**Issue by gau-ku** [cnr-isti-vclab/PyMeshLab#174]
Following the same steps that I perform in GUI to get a texture image, I am unable to do so with pymeshlab. 

So far, I've observed the issues with these two filters
1.  _project_active_rasters_color_to_current_mesh_filling_the_texture_
2. _parameterization__texturing_from_registered_rasters_

Without these, I'm unable to obtain the texture images. 

```
import os
import pymeshlab

p_path = "./assets/"
ms = pymeshlab.MeshSet()
ms.load_new_mesh(os.path.join(p_path, "garment.obj"))
rasters = sorted([i for i in next(os.walk(p_path))[2] if i.endswith(".png")])
for i in rasters:
    ms.load_new_raster(os.path.join(p_path, i))

ms.apply_filter('import_cameras_for_active_rasters_from_file',
                importfile = os.path.join(p_path, 'cams.out'))
ms.apply_filter('parameterization__texturing_from_registered_rasters',
                texturesize = 256,
                texturename = os.path.join(p_path, 'out_tex.jpg'))
```

Assets - [here](https://drive.google.com/file/d/1jX2wP42JJFGTEOvZ7Vfd2QCWjouyk4Fb/view?usp=sharing)

**Comment by alemuntoni** [comment]
Hi, which version of meshlab and which version of pymeshlab are you using? 
Last versions of meshlab and pymeshlab do not store anymore textures in the disk, but in memory along with meshes.
Therefore, in the last version of pymeshlab, you need to:
- give to the filter `parameterization__texturing_from_registered_rasters` just the name of the texture, without the path; e.g.: 
```
ms.parameterization__texturing_from_registered_rasters(
                texturesize = 256,
                texturename = 'out_tex.jpg')
```
- save the mesh to a format that handles textures after applying the filter, for example `obj`. Automatically, also the texture files will be saved.

Starting from the next version of pymeshlab, will be also possible to save only the texture, without saving the mesh.
