### ISSUE TITLE
Compute Planar Section and compute_planar_section Inconsistencies

### ISSUE THREAD

**Issue by alex-myers** [cnr-isti-vclab/PyMeshLab#175]
Hi,

I've noticed the compute_planar_section doesn't always work, but the correspond feature 
Filters -> Quality Measure & Computations -> Compute Planar Section
always works in MeshLab; even for noisy meshes.

I'm using MeshLab 2021.10 and pymeshlab-2021.10

When running and loading the mesh in PyMeshLab,
compute_planar_section

I get the exception

pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: compute_planar_section
Details: Mesh is not two manifold, cannot apply filter

However, the PyMeshLab filter does work for meshes that don't need repairing.

Here's a small mesh that can be used to reproduce the problem:
viablesoftwarellc.com/problem_mesh.stl

Here's my script:
```
import pymeshlab

# create a new MeshSet
ms = pymeshlab.MeshSet()

meshPath = "C://Users//Alex//meshes//problem_mesh.stl"
meshSavePath = "C://Users//Alex//meshes//problem_mesh_output.stl"

print("Loading new mesh " + meshPath)

# Load mesh
ms.load_new_mesh(meshPath)
print("finished loading")

# Apply plane cuts
ms.compute_planar_section(planeaxis=0, planeoffset=0.5, relativeto=1, createsectionsurface=False, splitsurfacewithsection=True)


# save mesh
ms.save_current_mesh(meshSavePath)
print("finished saving")
```

If there's some spots in the code you can point me to, I don't mind diving into this one.

_(edited: the orig post was just a link to a txt file. substituted with the txt file content)_

**Comment by alemuntoni** [comment]
Could you please upload the mesh that causes the issue?

**Comment by alex-myers** [comment]
[problem_mesh.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/7933901/problem_mesh.zip)

I'm taking down the STL from the website mentioned in the previous post.

**Comment by alemuntoni** [comment]
Ok, I couldn't download it from the website.
What do you mean with "However, the PyMeshLab filter does work for meshes that don't need repairing."?
I am trying to apply the filter with the same parameters both in meshlab and pymeshlab, and I always get the error that the surface is not two manifold and the filter cannot be applied.
I don't see how it should work with these parameters... The filter just requires two-manifoldness for its input mesh.

**Comment by alex-myers** [comment]
For the comment: "However, the PyMeshLab filter does work for meshes that don't need repairing."?
I've used some mesh files that aren't noisy, and the the compute planar section filter works fine in PyMeshLab 2021.10 and MeshLab 2021.10

When I use a noisy file, like the problem_mesh, PyMeshLab produces the error:

pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: compute_planar_section
Details: Mesh is not two manifold, cannot apply filter

I don't see the two manifold error on my side. It does apply the filter: See here.


So here's the problem mesh from that zip file:

![image](https://user-images.githubusercontent.com/6879182/151159044-316616f2-76c5-44be-b39a-833463a827e0.png)

Here's the filter I apply:
![image](https://user-images.githubusercontent.com/6879182/151159196-7bb05b3f-0ecd-4332-a81a-1b25d460c6d4.png)

Here's what's produced:
![image](https://user-images.githubusercontent.com/6879182/151159319-53ec7bdb-8722-4573-8848-aecf4fa01024.png)

I then clicked eyeballs 0, 1, and 3, to show what was produced.

![image](https://user-images.githubusercontent.com/6879182/151159390-4db10c3b-a026-48c7-8ec7-9399ba96bfcb.png)

Here's the mesh I just cut

[problem_mesh_filter_success.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/7941550/problem_mesh_filter_success.zip)

So, I am using Windows 10 for this. Are you using Mac or Linux?

I don't understand two-manifoldness even after some research. What does that mean, and is there a way to use PyMeshLab to make the mesh two-manifoldness?

**Comment by jmespadero** [comment]
Hi,

I can confirm that your mesh does not work in meshlab nor pymeshlab due to existence of non-manifold vertices due to duplicate vertices. 

This is a problem common when you save meshes to ASCII STL file format. You can easily solve this if you apply the filter `Merge Close Vertices` as soon as you load you mesh. My advise is to do this whenever you load from STL file format.

This is not a bug of meshlab, but of the program who saved the mesh in first place
