### ISSUE TITLE
Cut meshes/surfaces at intersection

### ISSUE THREAD

**Issue by andrea-bistacchi** [cnr-isti-vclab/PyMeshLab#177]
Hello, is it possible to cut a triangulated mesh/surface at the intersection with another one?

I don’t understand if the Boolean tools can be used in this way, particularly on open surfaces.

Thanks very much!

**Comment by jmespadero** [comment]
Hi,
Sorry to have to explain this, but the "issues" section should be used only to report a possible problem in the code to the developers, not for ask questions about the usage of the library. 
If you need help with meshlab/pymeshlab usage, try the "[discussion](https://github.com/cnr-isti-vclab/PyMeshLab/discussions)" section or the [stackoverflow page](https://stackoverflow.com/questions/tagged/pymeshlab).

**Comment by andrea-bistacchi** [comment]
Thanks! It's no always like that. Sorry.
