### ISSUE TITLE
reconstruction vcg normals

### ISSUE THREAD

**Issue by hanzbrech** [cnr-isti-vclab/PyMeshLab#189]
Hallo,

I reconstructed I think both times with VCG (generate_surface_reconstruction_vcg).

First time in MeshLab GUI, it saved with normals.

Second time in pymeshlab the automatically saved file had no normals after reconstruction.
Also its sad you can not give it a filename..

I can't recreate it now, because my point cloud is to big and Im still working on getting a good automated result.... And im not a 100% sure anymore if I really used the same recon allgo but im 99% sure.

But just wanted to let you know, if its wrong you can just delete this Issue

AND:
voxsize = pymeshlab.AbsoluteValue(0.02), openresult = False, mergecolor = True, subdiv = 3

crashes on my PC without any Error when refilling the 2. Block. And it tells me in Commandline its saving file 000 but it doesn't no file creation goes to 2. block does stuff tries to fill crash without any feedback

**Comment by alemuntoni** [comment]
Hi, sorry for the late reply.
I am not able to reproduce the issues you are describing.
What do you mean with "you can not give it a filename"? You can save meshes in any format giving the filename you prefer. Just take a quick look to the documentation (there are also tutorials). And in the documentation are described also the options for saving normals or other components.
For crashes, if you can provide at least a piece of code and a small input mesh example, it would help us reproducing the issue.
