### ISSUE TITLE
delete_current_mesh() after copying a mesh causes segmentation fault in Ubuntu

### ISSUE THREAD

**Issue by mvgician** [cnr-isti-vclab/PyMeshLab#190]
Hi,

I've been experiencing a similar problem as the one described in #172. 

Whenever I try to delete the original mesh using `delete_current_mesh()` after copying it with `generate_copy_of_current_mesh()`, it causes a segmentation fault. This only happens to me while using Ubuntu 20.04 (focal) in a Docker container, it works fine in Windows 11.

I've setup a small Dockerfile and Python script to showcase this issue:

Dockerfile contents:
```
FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /test
RUN apt-get -qq -y update && \
	apt-get install -qq -y mesa-common-dev libglu1-mesa-dev libgmp-dev libcgal-dev libboost-all-dev libglib2.0-0 python3-pip && \
	pip install pymeshlab==2022.02

COPY segfault.py /test
CMD ["python3", "-u", "segfault.py"]
```
`segfault.py` contents:

```
import pymeshlab as pm

ms = pm.MeshSet()
print("setting verbosity to true...")
ms.set_verbosity(True)
print("creating cube...")
ms.create_cube()
print("generating copy...")
ms.generate_copy_of_current_mesh()
print("setting original cube as current mesh...")
ms.set_current_mesh(0)
print("deleting original cube...")
ms.delete_current_mesh()
print("printing status...")
ms.print_status()
print("done")
```
Building and running commands:
```
docker build -t pymeshlab-bug .
docker run --name pymeshlab-bug -it pymeshlab-bug
```

Expected behaviour (Windows 11):

```
setting verbosity to true...
creating cube...

Applying filter create_cube with the following parameters:
{'size': 1.0}

LOG: 2 create_cube applied!    [ 100% ]

generating copy...

Applying filter generate_copy_of_current_mesh with the following parameters:
{}

LOG: 2 Duplicated current model to layer 1

setting original cube as current mesh...
deleting original cube...

Applying filter delete_current_mesh with the following parameters:
{}


printing status...
Number meshes: 1
        Mesh id: 1
        Mesh label: Box/Cube_copy
        Full name:

done
```

Failing behaviour:
```
setting verbosity to true...
creating cube...

Applying filter create_cube with the following parameters:
{'size': 1.0}

LOG: 2 create_cube applied!    [ 100% ]

generating copy...

Applying filter generate_copy_of_current_mesh with the following parameters:
{}

LOG: 2 Duplicated current model to layer 1

setting original cube as current mesh...
deleting original cube...

Applying filter delete_current_mesh with the following parameters:
{}

Segmentation fault
```
It's a rather specific scenario and I can easily work around it, but I'd appreciate any feedback on this.

P.S: Using the docker run command as I described it won't print out "Segmentation fault" and just end the program. I think it has to do something with the stderr being unbuffered or whatnot. Running the script from bash does display it.

**Comment by alemuntoni** [comment]
Hi, thanks for reporting!
The issue has been introduced with the last version of meshlab, and we will release ASAP a patch for the last version of pymeshlab! I'll write here when it will be released!

**Comment by alemuntoni** [comment]
Fixed, with the last post-release.
Just run

```
pip install pymeshlab --upgrade
```
to upgrade pymeshlab to version 2022.2.post2
