### ISSUE TITLE
Segmentation fault when calling ms.delete_current_mesh() in POP_Os

### ISSUE THREAD

**Issue by jabrucohee** [cnr-isti-vclab/PyMeshLab#194]
Hey there, first of thank you very much for all the cool new features, introduced with the new version!  I have been using pymeshlab to build a tool with which we hope to reconstruct surfaces of cells and biological material, it works quite well so far. But I have a small issue to report. When running the following code in POP_OS 21.10

    import pymeshlab
    import numpy as np

    def main():

          ms = pymeshlab.MeshSet()
          ms.load_new_mesh('Experiment-78+pointcloud.ply')
          ms.set_current_mesh(0)
          ms.compute_normal_for_point_clouds(k=50, smoothiter=3, flipflag=True, viewpos=[14.6, 16.32, 7.46])
          sub_sampling_points = int(0.25*ms.current_mesh().vertex_number())
          print(sub_sampling_points)
          ms.generate_simplified_point_cloud(samplenum=sub_sampling_points, radius=pymeshlab.Percentage(0.231))
          ms.set_current_mesh(0)
          print(ms.mesh_id_exists(0))
      
          print('check')
          ms.delete_current_mesh()
          print('check')

    if __name__ == '__main__':
          main()

the line ms.delete_current_mesh(), seems to throw a segmentation fault. This does not happen if one line above, I change ms.set_current_mesh( 0 )-> ms.set_current_mesh(1). Also, the code does work in Ubuntu 21.10. (POP_Os is based on Ubuntu.) I am not sure if this is the right place to ask for advice, but I do not really know how to fix this and also not where else to ask. 

I appreciate any help to fix this.

**Comment by alemuntoni** [comment]
Hi,
just run 
```
pip install pymeshlab --upgrade
```
a fix for this issue has been just released.
