### ISSUE TITLE
pmeshlab.set_max_gpu_memory available only in the 0.1.8 version

### ISSUE THREAD

**Issue by fblistein** [cnr-isti-vclab/PyMeshLab#198]
Hello all,

I noticed that the `set_max_gpu_memory()` function from the `pmeshlab `module member is available only in the 0.1.8 version.
See here :
https://pymeshlab.readthedocs.io/en/0.1.8/classes/pmeshlab.html#pmeshlab.set_max_gpu_memory

Has this been replaced with something else in newer versions ?

Best,

François

**Comment by alemuntoni** [comment]
Hi, it has been removed since it was a functionality that actually worked only on a small set of gpu.
