### ISSUE TITLE
Wanted to try meshlab on openSuSE Leap 15.2

### ISSUE THREAD

**Issue by azalanono** [cnr-isti-vclab/PyMeshLab#201]
Hello. 
Yesterday I wanted to try Meshlab AppImage on my openSuSE Leap 15.2 (x64). 

Does not even start up because it requires a higher version of glibc.

I really wonder how one can get this super-smart idea to use late(st) lib versions and hereby locking out many users.

Can I somehow get an AppImage running? Or - other approach - which AppImage version will run on my system (and how to download that one)?

**Comment by alemuntoni** [comment]
Hi,
unfortunately, openSuSE Leap 15.2 reached its end of life on jan 4, therefore it is not supported anymore.
We have limited resources in our lab: we use what github puts at our disposal, which is Ubuntu. For building AppImages, we use the oldest still supported lts, which is 18.04. We just cannot use other distros.
To use meshlab in your distro, you'll have to built it by yourself (we provide scripts to automatically do that, and you can check also github actions workflows).
P.S. Note that this is the PyMeshLab repository, not MeshLab.
