### ISSUE TITLE
SDF filter

### ISSUE THREAD

**Issue by guillermoAlv** [cnr-isti-vclab/PyMeshLab#206]
Hi, I'm trying to use `compute_scalar_by_shape_diameter_function_per_vertex()` but I can't generate nothing, the mtl file generated have just one color. 
You can find my code and execute yourself [here](https://colab.research.google.com/drive/1eCdlNIBSIvH6Xu-nZjuYhliQd90pT6pQ?usp=sharing)
Probably I'm doing something wrong but I don't know what.

**Comment by alemuntoni** [comment]
Hi, sorry for the very late reply.
This is probably due to the fact that some servers do not allow to run code that use GPU. The shape diameter function filter uses OpenGL to compute the function... But the weird thing is that the filter should fail..

**Comment by alemuntoni** [comment]
Hi, sorry again for the late reply.
I guess that something changed from the last time I checked. 
If this issue still apply, could you please share the input models used in the script? I cannot find them anywhere (also running the script complains because they are missing).

**Comment by guillermoAlv** [comment]
Hi, It seems that the issue is solved now.
Thanks a lot!
