### ISSUE TITLE
texel_sampling is not working

### ISSUE THREAD

**Issue by hironoriyh** [cnr-isti-vclab/PyMeshLab#21]
Thanks for providing this library.
I'd like to upsample pointcloud color by meshlab and ran the following code.

```
import pymeshlab as ml
ms = ml.MeshSet()
ms.load_new_mesh('test.obj')
ms.apply_filter('texel_sampling', recovercolor=True)
ms.save_current_mesh('pytest.ply', binary=False, save_vertex_color=True, save_face_color=False)
```

and I got the following error. Do you know what's wrong with this?

```
PyMeshLab 0.1.6 based on MeshLab 2020.09d
Similar Triangles face sampling
Floating point exception
```

FYI, here is the issue from meshlab repo.
https://github.com/cnr-isti-vclab/meshlab/issues/272

**Comment by alemuntoni** [comment]
Hi @hironoriyh, thanks for reporting.
I don't see how https://github.com/cnr-isti-vclab/meshlab/issues/272 is related with this issue, since a different filter is causing the problem.
Could you please share a mesh that reproduces the issue?
