### ISSUE TITLE
[MAC OS] PyMeshLab: "surface_reconstruction_screened_poisson" not in listed filters 

### ISSUE THREAD

**Issue by evangabe** [cnr-isti-vclab/PyMeshLab#22]
Hi,

After printing the filter list it seems that the "surface_reconstruction_screened_poisson" filter is not available to apply on meshes despite being listed on the readthedocs webpage. Is there any chance this filter could be re-added?

Thanks

**Comment by alemuntoni** [comment]
Hi, it should be there! 
Could you please tell which platform are you using?

**Comment by alemuntoni** [comment]
Tested, and the filter it is correctly loaded on my mac.
Could you please share the output of the following commands:
```
ms = pymeshlab.MeshSet(True)
ms.print_plugin_list()
```

Thanks!

**Comment by evangabe** [comment]
This is the output I received:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
QCoreApplication::applicationDirPath: Please instantiate the QApplication
object first
The base dir is /
Meshlab Initialization: Serious error. Unable to find the plugins directory.
QCoreApplication::applicationDirPath: Please instantiate the QApplication
object first
The base dir is /
Current Plugins Dir is:
/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns

QAction: Initialize QApplication before calling 'setShortcut'.
"Cannot load library
/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libfilter_csg.so:
(dlopen(/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libfilter_csg.so,
133): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib\n
 Referenced from:
/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libfilter_csg.so\n
 Reason: image not found)"
"Cannot load library
/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libfilter_isoparametrization.so:
(dlopen(/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libfilter_isoparametrization.so,
133): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n
 Referenced from:
/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libfilter_isoparametrization.so\n
 Reason: image not found)"
*"Cannot load library
/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libfilter_screened_poisson.so:
(dlopen(/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libfilter_screened_poisson.so,
133): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n
 Referenced from:
/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libfilter_screened_poisson.so\n
 Reason: image not found)"*
"Cannot load library
/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libglobalregistration.so:
(dlopen(/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libglobalregistration.so,
133): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n
 Referenced from:
/Users/evangabrielson/PycharmProjects/pythonProject/venv/lib/python3.7/site-packages/pymeshlab/PlugIns/libglobalregistration.so\n
 Reason: image not found)"
MeshSet class - list of loaded plugins (45):
FilterAmbientOcclusion
FilterCamera
FilterClean
FilterColorProjection
FilterColorProc
FilterCreate
FilterCreateIso
FilterDirt
FilterFractal
FilterFunc
FilterGeodesic
FilterImagePatchParametrization
FilterLayer
FilterMeasure
FilterMeshing
FilterMLS
FilterMutualGlobal
FilterMutualInfo
FilterPlyMC
FilterQHull
FilterQuality
FilterSample
FilterSampleDyn
FilterSampleGPU
FilterSampling
FilterSDFGPU
FlterSelect
FilterSketchFab
FilterSSynth
FilterTexture
FilterTriOptimize
FilterUnsharp
FilterVoronoi
IO3DS
IOBase
IOBRE
IOCollada
IOCTM
IOExpe
IOJson
IOPDB
IOTRI
IOTXT
IOU3D
IOX3D
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Let me know how I should proceed to load that filter.

**Comment by alemuntoni** [comment]
Ok, I see. This is quite annoying!
Running 
```
brew install libomp
```

should fix the issue, but I'll try to avoid this required installations in future versions.
Before installing libomp, could you check for me if the filter "screened poisson" is available in the last 2020.12 MeshLab in your system? Thanks!

**Comment by alemuntoni** [comment]
Fixed on commit b7702a7860855e67a9314a8b963644b2fd829516. It will be available on next version of pymeshlab which I plan to release shortly. In the meantime, `brew install libomp` should fix the issue!

**Comment by evangabe** [comment]
Thanks Alessandro,

This worked great! I am currently looking for some animation functionality
in MeshLab and am not sure if it exists or not as it wasn't on the
documentation website. I want to be able to have my model spin along the
z-axis so that I can showcase my work. Is this possible? If so, where
should I be looking in?

-Evan

**Comment by alemuntoni** [comment]
No, sorry. As far as I know, there are no animation functionalities in MeshLab.
