### ISSUE TITLE
meshing_decimation_quadric_edge_collapse

### ISSUE THREAD

**Issue by LogWell** [cnr-isti-vclab/PyMeshLab#220]
How to get indices into F of birth face like [igl::qslim](https://github.com/libigl/libigl/blob/2869f9862926ef6e6acc5e2fa0b51f8fd165e22f/include/igl/qslim.h#L31)?

**Comment by cignoni** [comment]
There are various info that could be exposed from internal in our old faithful quadric simplifier. What exactly are the birth face in igl::qslim? is it the order in which the faces are deleted?
