### ISSUE TITLE
The change of running speed is not constant

### ISSUE THREAD

**Issue by lancexiang** [cnr-isti-vclab/PyMeshLab#223]
In some case, i find the speed of pymeshlab code snipest elapsed very different time-consume. And i tested simply to verify this. In experiment1(test1.py): i run the code tempelate:
```
code1 
code2
pymeshlab code  # elapsed 60s
```
In experiment2(test2.py): i run the code tempelate:
```
pymeshlab code # same code elapsed 20s
```
Now i don't know how to debug this. Is there any package (e.g. vtk, pymesh) would influence the time-consume?

**Comment by alemuntoni** [comment]
Really hard to debug this without having an example to reproduce.
Other packages should not have any influence, but I really don't know if CPython need extra care in some cases.
