### ISSUE TITLE
different speed in different platform

### ISSUE THREAD

**Issue by lancexiang** [cnr-isti-vclab/PyMeshLab#224]
with same mesh file, i tested in MacOS, Windows, Linux with loop subvision and decimate, here are results:
macos and windows:
```
vertex: 321098, faces: 642208
loop:  10.47s
decimate:  8.97s
```
while linux
```
vertex: 321098, faces: 642208
loop:  35.74s
decimate:  21.39s
```
I don't know what happens and how to fix the linux time-consume.

**Comment by alemuntoni** [comment]
Just to be sure, are you using the same machine but with different OS? 
Could you please share the mesh and the code you are running?
