### ISSUE TITLE
Exported .obj file missing image texture in Material

### ISSUE THREAD

**Issue by methot-ilya-3ds** [cnr-isti-vclab/PyMeshLab#227]
I've tested exporting an object in the same way directly from Meshlab, and using PyMeshLab and the PyMeshLab .obj export does not use the exported texture in its material.

In the following images you can see (left) the .obj file exported from PyMeshLab which is missing the image texture and (right) the .obj file exported directly from MeshLab which contains the image texture

![image](https://user-images.githubusercontent.com/64415447/173368653-ddbda7c6-20e5-4d07-aaf6-91c4a1ab864c.png)
![image](https://user-images.githubusercontent.com/64415447/173368945-4efa3d49-9113-477b-986e-aa450b206093.png)

**Comment by alemuntoni** [comment]
Probably duplicated of #207.
Could you please be more specific?
Which platform are you using? Could you please share a piece of code and a model that reproduces the issue?

**Comment by methot-ilya-3ds** [comment]
Just Looked at #207 and this is indeed a duplicate. When I changed the direct path in the .obj file it loaded correctly.
