### ISSUE TITLE
Windows install of pymeshlab with python embedable 64bit

### ISSUE THREAD

**Issue by GridLogicMichigan** [cnr-isti-vclab/PyMeshLab#23]
I keep getting the following error: 
```
AttributeError: module 'pymeshlab' has no attribute 'MeshSet'
```

get this when running the pytest as well as the following:

```
import pymeshlab as ml
ms = ml.MeshSet()

ms.load_new_mesh('keystone.stl')
ms.save_current_mesh('keystone.obj')
```

**Comment by alemuntoni** [comment]
It seems that pymeshlab is not installed correctly.
Could you try to run
```
pip3 uninstall pymeshlab
pip3 install git+https://github.com/cnr-isti-vclab/PyMeshLab
```

and paste here the output of the installation?
Be sure to use a version of python >= 3.6 and <= 3.8

**Comment by GridLogicMichigan** [comment]
I did exactly as you specified I uninstalled and reinstalled.
In installed fine, it also runs fine in the python shell on the windows command-line:
```
C:\Users\Craig\Desktop\New folder\Libraries\python-3.8.6-embed-amd64>python.exe
-m pip install git+https://github.com/cnr-isti-vclab/PyMeshLab
Collecting git+https://github.com/cnr-isti-vclab/PyMeshLab
  Cloning https://github.com/cnr-isti-vclab/PyMeshLab to c:\users\craig\appdata\
local\temp\pip-req-build-gqd6mals
Requirement already satisfied: numpy in c:\users\craig\desktop\new folder\librar
ies\python-3.8.6-embed-amd64\lib\site-packages (from pymeshlab==0.1.6) (1.19.4)
Building wheels for collected packages: pymeshlab
  Building wheel for pymeshlab (setup.py) ... done
  Created wheel for pymeshlab: filename=pymeshlab-0.1.6-py3-none-any.whl size=27823968 sha256=24df003b59d3c9a157147caa4b25faaac12dfb03c783ac187fe3b3c00727b072
  Stored in directory: C:\Users\Craig\AppData\Local\Temp\pip-ephem-wheel-cache-w8fxncxx\wheels\74\72\3e\dde001df05a3c88b2bdbad8c37cb1b791906c5a4f991b0ae2e
Successfully built pymeshlab
Installing collected packages: pymeshlab
Successfully installed pymeshlab-0.1.6
WARNING: You are using pip version 20.3; however, version 20.3.1 is available.
You should consider upgrading via the 'C:\Users\Craig\Desktop\New folder\Librari
es\python-3.8.6-embed-amd64\python.exe -m pip install --upgrade pip' command.

C:\Users\Craig\Desktop\New folder\Libraries\python-3.8.6-embed-amd64>python.exe
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymeshlab as ml
PyMeshLab 0.1.6 based on MeshLab 2020.09d
>>> ms = ml.MeshSet()
>>> exit()

C:\Users\Craig\Desktop\New folder\Libraries\python-3.8.6-embed-amd64>
```

however running in a script I get:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Craig\Desktop\New folder\Libraries\python-3.8.6-embed-amd64\lib\site-packages\pymeshlab\__init__.py", line 1, in <module>
    from .pmeshlab import *
ImportError: DLL load failed while importing pmeshlab: The specified module could not be found.
```

When I clear out the __init__py file I get:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pymeshlab' has no attribute 'MeshSet'
```

**Comment by alemuntoni** [comment]
You should not remove `__init__.py` file.
Could you check if the dll having name that starts with `pmeshlab` is present inside the pymeshlab package directory?
Also, what happens if you try to import pymeshlab from a python shell?

**Comment by GridLogicMichigan** [comment]
Yes  I only removed contents of the file for diagnostics..   The module works from a script on a command line,  but being called form another application is where it breaks.  I am a linux person so python in windows is a challenge.  I think the issue could be a PATH issue.  But I am not having issues with any other modules I import,  only this one.

**Comment by alemuntoni** [comment]
Well, knowing nothing about this application that is calling pymeshlab it is difficult to understand even if the issue is related with pymeshlab.. I just cannot replicate the issue.

**Comment by GridLogicMichigan** [comment]
Thank you.   I only decided to post here when I discovered the issued only happens with this module.  But its likely not an issue with the module after further testing.

**Comment by HollowHeartNet** [comment]
@GridLogicMichigan Did you solve this issue? If yes, please tell me how since I have the same problem on windows.

**Comment by GridLogicMichigan** [comment]
Hi,

I have not resolved this.  I have set this aside since I had no other feedback from anyone.


Thanks
David



On Mar 20, 2021, at 10:21 PM, HollowHeartNet ***@***.***> wrote:

﻿

@GridLogicMichigan<https://github.com/GridLogicMichigan> Did you solve this issue? If yes, please tell me how since I have the same problem on windows.

**Comment by tryba** [comment]
I encountered this same error on Windows 10 where pymeshlab was a transitive dependency of this import
```
from nerf.provider import NeRFDataset
```
I imported pymeshlab directly before this line and worked around the issue. I did not dig further into what downstream state change causes the DLL failure.
