### ISSUE TITLE
How to save snapshots of the cloud points?

### ISSUE THREAD

**Issue by hwj05140514** [cnr-isti-vclab/PyMeshLab#230]
Hello, I got a problem when I wanted to apply the filter ,"save_snapshot" to the cloud points. The error was "number of vertices less than three or zero number of faces on selected mesh". I loaded the cloud points from ".txt" file，only containing "x,y,z" information. Does it mean I can't take  snapshots on the cloud points?

**Comment by hwj05140514** [comment]
> 

OK.Thanks.

**Comment by alemuntoni** [comment]
Closing as duplicate of #164. Refer to that issue for further details.
