### ISSUE TITLE
edge_matrix empty for all meshes

### ISSUE THREAD

**Issue by zoyt** [cnr-isti-vclab/PyMeshLab#231]
Hi,

I am looking to use mesh edge information, but found that pymeshlab returns an empty array for all meshes I've thrown to it thus far. I'm using version 2022.2, here's a quick reproduceable example:

```python
ms = ml.MeshSet()
ms.apply_filter("create_sphere")
m = ms.current_mesh()
allVerts = m.vertex_matrix() # array of vert coordinates
allFaces = m.face_matrix() # array of which verts make up a face
allEdges = m.edge_matrix()
```
allEdges, for this mesh and all other meshes that I have tested, returns as:
```python
array([], shape=(0, 2), dtype=int32)
```
All other _matrix calls work perfectly, and this feature has been implemented for [a few months](https://github.com/cnr-isti-vclab/PyMeshLab/issues/158) so I assume it to have been working for other folks, but I can't identify what that would be even in such a simple test case, so I believe something to be internally awry.

Could anyone please point me to what I am doing wrong, or a possible fix?

Thanks!

**Comment by danwbean** [comment]
A sphere does not have an edge, hence the empty result.
It works correctly for a mesh containing an edge.

**Comment by alemuntoni** [comment]
@danwbean is right. Edges are "extra elements" that are not intrinsically encoded in the mesh triangles. There are several filters that computes them, like the one that computes polylines.
If you are looking for all the edges composing triangles of the mesh, they are encoded in the face matrix, and you need to extract them from it.

**Comment by zoyt** [comment]
Thanks for the closure on this, I have to imagine this isn't the first time that the double meaning of edge in mesh processing has raised eyebrows before. In case anyone else is looking for this in the future, this is the code I wrote to expose the data I was after, which were the half-edges that make up the triangles, and which faces those half-edges belonged to. 

```python
faceMatrix = ms.mesh(1).face_matrix()

 voro_face_half_edges = {}
 for face, (v0, v1, v2) in enumerate(faceMatrix):
     voro_face_half_edges[face] = [(v0, v1), (v1, v2),  (v2, v0)]

 faceOfHalfEdge = {}
 faceOfHalfEdgeTwin = {}

 for face, (halfEdge1, halfEdge2, halfEdge3) in enumerate(voro_face_half_edges.values()):
     faceOfHalfEdge[halfEdge1] = face
     faceOfHalfEdge[halfEdge2] = face
     faceOfHalfEdge[halfEdge3] = face

     faceOfHalfEdgeTwin[halfEdge1[::-1]] = face
     faceOfHalfEdgeTwin[halfEdge2[::-1]] = face
     faceOfHalfEdgeTwin[halfEdge3[::-1]] = face

```
