### ISSUE TITLE
Edge_matrix not exposed

### ISSUE THREAD

**Issue by danwbean** [cnr-isti-vclab/PyMeshLab#238]
I am splitting a watertight mesh of a spear point into upper and lower halves using conditional face selection (fnz > 0). My goal is to extract the _ordered_ polyline representing the common edge between the two halves.

![overview_ppt](https://user-images.githubusercontent.com/25962619/180613740-42f6bbef-3d35-4470-a170-4cc0c3f19b19.png)
Initial watertight mesh

![green_edges](https://user-images.githubusercontent.com/25962619/180614055-e4472f20-7b7d-44fb-b233-134ea0615c0a.png)
Subset mesh of upper half only.  The goal is to expose edge matrix of upper surface (green polyline)

Here is the code:
```
import pymeshlab

watertight_mesh = '/home/dan/GLiMR_Projects/G3/ply_files/ply_test/G1566_top.ply'

ms = pymeshlab.MeshSet()
ms.load_new_mesh(watertight_mesh)       # current mesh is lying flat in XY plane, thickness = Z

ms.apply_filter('compute_selection_by_condition_per_face', condselect='(fnz > 0)')  # select upper surface
ms.apply_filter('generate_from_selected_faces', deleteoriginal=False)

m = ms.current_mesh()       # want polyline of edge of this mesh

print(m.vertex_number(), 'vertices')        # 77222 vertices
print(m.face_number(), 'faces')             # 152461 faces
print(m.edge_number(), 'edges')             # 0 edges   (does not expose edges; m.edge_matrix() is empty)
```

**m.edge_matrix** is empty.   This works manually in MeshLab, just not in PyMeshLab
Preserving vertex order will be important.     Thanks.

**Comment by alemuntoni** [comment]
@danwbean sorry for the very late reply. Could you please share the mesh you are using in order to replicate the issue?
Thanks.

**Comment by danwbean** [comment]
Hello,

Thanks for all of your efforts on this wonderful program!  I am using it in
archaeological shape analysis on stone spear points.

About the problem: The mesh used is unimportant.  This filter always
returns an empty dict.  Here is an example just using a tetrahedron as the
mesh.

Thanks,

Dan Bean
Corvallis, Oregon, USA

import pymeshlab

ms = pymeshlab.MeshSet()

ms.create_tetrahedron()
ms.apply_filter('set_selection_all')

result = ms.apply_filter('compute_matrix_by_fitting_to_plane',

targetplane='XY plane',

rotaxis='any axis',

toorigin=False,

freeze=True,

alllayers=True)


print('\nresult of
ms.apply_filter("compute_matrix_by_fitting_to_plane":\n', result)        #
result = {}

**Comment by danwbean** [comment]
It is still difficult to access polyline information from PyMeshLab.  Polylines derived from PyMeshLab are useful for many analytical purposes outside of MeshLab, but they are difficult to extract and **preserve vertex order**.

An ordered numpy array (n, 3) representing the polyline (x,y,z) is what is typically used outside.  Providing an ordered array of indices into m.vertex_matrix() would solve our problem.  The edge_matrix would contain this.

Currently **edge_matrix is not populated**, so I have to rebuild the polyline from unsorted vertices.

Here is a a simpler example.  A sphere_cap has an edge:
```
import pymeshlab

ms = pymeshlab.MeshSet()
ms.create_sphere_cap()
m = ms.current_mesh()
print(m.edge_matrix())
```

**_m.edge_matrix() is empty []_**

The goal is to extract the vertices in order to form a 3D polyline.

Thanks again.. Great program.

**Comment by alemuntoni** [comment]
I think that this is something that needs to be clarified in the documentation, [I just did it](https://github.com/cnr-isti-vclab/PyMeshLab/commit/ec28906ef94aff28e62e07f35411514e010aab29).
I don't know if I'm right, but it seems to me that you're calling polyline the border of a non-watertight mesh. This is not always true.
You could generate polylines using other from other criteria (e.g. the border of a selection). 
In general, the Edge Matrix in VCGLib, MeshLab and PyMeshLab it is not related and has nothing to do with the the mesh faces. 
Edges are other elements that could be computed using some filters, or added manually.

In your specific case, I think that the filter `generate_polyline_from_selection_perimeter` could do what you need, after computing the selection using `compute_selection_by_condition_per_face`. 
You can do some tests interactively with meshlab to see if this is what you need.
The filter `generate_polyline_from_selection_perimeter` will compute a new mesh having 0 faces and a list of edges representing the polyline(s) computed starting from the selection of the previous mesh.

**Comment by danwbean** [comment]
Alessandro,

Thank you for the quick reply.  You were correct: I was mixing up edges
versus borders.  I am interested in borders. The workflow you describe is
what I am using and it yields the correct vertex set.  The issue is *preserving
vertex order*. The order of the array is not the sequential order of the
vertices in the polyline.  I am currently reassembling the polyline from
the unsorted vertices.

*Is there a way to recover the vertex order of the polyline vertices?*

In my application I am starting with a watertight mesh representing an
archaeological stone projectile point.  I use polylines in two main ways:

   - I split the watertight mesh into top and bottom faces based on face
   normals selection and create the selection border polyline
   - I generate cross-sections of the mesh using compute_planar_section.

In each case I need the vertices in polyline order.  How do I accomplish
this?

Thanks

Dan Bean
Corvallis, OR, USA
