### ISSUE TITLE
'compute_matrix_by_fitting_to_plane' filter returns an empty dict

### ISSUE THREAD

**Issue by danwbean** [cnr-isti-vclab/PyMeshLab#239]
If you apply filter 'compute_matrix_by_fitting_to_plane'  with verbosity=True, the rotation results are shown in the output.  

_LOG: 2 Using 1758 vertices to build a fitting plane
LOG: 2 Fitting Plane avg error is 0.314092
LOG: 2 Fitting Plane normal is [-0.000492, 0.004511, 0.999990]
LOG: 2 Rotation axis is [-0.994110, -0.108378, 0.000000]
LOG: 2 Rotation angle is -0.004537_

**The filter currently does not populate and return a dict with rotation info or return the rotation matrix.**

I have a work-around...  No rush.   Wonderful software!

**Comment by alemuntoni** [comment]
Fixed in the last commit of devel branch!

**Comment by danwbean** [comment]
Alessandro,

Thanks you very much!

Dan Bean
