### ISSUE TITLE
Get list of mesh ids in a meshset

### ISSUE THREAD

**Issue by markarenillo** [cnr-isti-vclab/PyMeshLab#240]
Is there a way to get a list if mesh ids in a meshset? Thank you

**Comment by alemuntoni** [comment]
Just compute the list of ids. The MeshSet [allows to iterate over the meshes](https://pymeshlab.readthedocs.io/en/latest/classes/meshset.html#pmeshlab.MeshSet.__iter__), and the Mesh [has a method that returns the id of the mesh](https://pymeshlab.readthedocs.io/en/latest/classes/mesh.html#pmeshlab.Mesh.id).
