### ISSUE TITLE
How to convert texture coordinates to pixel coordinates by pymeshlab

### ISSUE THREAD

**Issue by ziwenjie** [cnr-isti-vclab/PyMeshLab#244]
I got the wedge texture coordiantes, and I want to get the wedge's pixel coordinate of texture map.

**Comment by alemuntoni** [comment]
You can just multiply a texture coordinate by the size of the texture to get the index of the pixel. 
You can get the texture of a mesh using the `texture` method of the  class `Mesh`.

**Comment by LFaggi** [comment]
> You can just multiply a texture coordinate by the size of the texture to get the index of the pixel. You can get the texture of a mesh using the `texture` method of the class `Mesh`.

In case I have a mesh with several textures, how do I know which texture the particular uv coordinates refer to? There seems to be no way to access this information directly.
When opening the same mesh in MeshLab, mesh faces have a custom scalar attribute named "materialIndex". Thus I tried to access `mesh.face_custom_scalar_attribute_array("materialIndex")`, but this attribute does not exist.
