### ISSUE TITLE
ImportError: libglib-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MikoSamey** [cnr-isti-vclab/PyMeshLab#245]
Hello! I am having a go at getting PyMeshLab installed on Linux.
I used `pip3 install pymeshlab` to install.Everything seems to install fine - however when I try to load the module I get the following error:
```
(icon) root:/# python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymeshlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/envs/icon/lib/python3.8/site-packages/pymeshlab/__init__.py", line 14, in <module>
    from .pmeshlab import *
ImportError: libglib-2.0.so.0: cannot open shared object file: No such file or directory
```
I also used `apt update && apt install --yes libgl1-mesa-dev` as you mentioned in Issues `ImportError: libGL.so.1: cannot open`
But it didn't work.

Strangely, I also installed pymeshlab==0.2.1 in another Linux,for it's GLIBC_2.23.It's runnable,and it does not have this file `libglib-2.0.so.0`

Do you have any suggestions for how I can get this running?

Thanks!

**Comment by luke23571113** [comment]
Got a very similar error on mac after successfully installing.

`Traceback (most recent call last):
  File "remesh.py", line 1, in <module>
    import pymeshlab 
  File "/Users/luke/Documents/dataset-testing/env/lib/python3.8/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'`

**Comment by alemuntoni** [comment]
See #157.
