### ISSUE TITLE
Save_snapshot filter doesn't take to accout vertex colors

### ISSUE THREAD

**Issue by NikitaSkoblov** [cnr-isti-vclab/PyMeshLab#248]
Hi!

I want to create some rasters from high-polygonal non-textured 3D model. To do it, I open it from ".ply" file and trying to position it and perfrom "save_snapshot" filter. It creates pictures with proper view but doesn't take to account per-vertext colors. So, on generated image mesh it is always gray-colored.

Should I enable vertex coloring someshere for that or "save_snapshot" doesn't support that at all? Is there any workarounds for that task?

Thank you!

**Comment by alemuntoni** [comment]
See #164
