### ISSUE TITLE
meshing_decimation_quadric_edge_collapse:extra line segments appear

### ISSUE THREAD

**Issue by minmin518** [cnr-isti-vclab/PyMeshLab#250]
Using meshing_decimation_quadric_edge_collapse filter, targetfacenum=100000 is set, and other parameters are default values. For some Meshes, an extra line segment will appear after simplification. After optimalplacement is set to False, the extra line segment will disappear. Would like to know why this is happening, thanks a lot!

**Comment by alemuntoni** [comment]
Could you please share a in input mesh and a piece of code that allows to reproduce the issue? thanks.
