### ISSUE TITLE
a diiference between meshlab and pymeshlab

### ISSUE THREAD

**Issue by zhDai** [cnr-isti-vclab/PyMeshLab#252]
hi. 
I have a stl, i show it on meshlab:
Vertices: 379,251
Faces: 757,616
then I use the button  which is "remove_duplicate_vertices", it becomes as:
Vertices: 370,280
Faces: 757,616
___________________________________________
however, when i use 'remove_duplicate_vertices' by pymeshlab, it becomes as:
Vertices: 377577
Faces: 757,616

so,  how can i fix it. Looking forword for your replying.

**Comment by alemuntoni** [comment]
See my reply to #249. The issue is the same here: when deleting duplicate vertices, some vertices that were "duplicates" with float precision, were not anymore using double precision.
