### ISSUE TITLE
scale dependent quadric fitting does not work after splitting into connected components

### ISSUE THREAD

**Issue by jabrucohee** [cnr-isti-vclab/PyMeshLab#256]
Hey there I get very consistently, if I first apply the filter  

`generate_splitting_by_connected_components`

and then the filter

`compute_curvature_principal_directions_per_vertex(methid=4)`

that the runtime for the calculation becomes really long. Before the calculation time was a few seconds (without splitting in connected components) afterwards I always interupted the kernel after an hour or so

**Comment by alemuntoni** [comment]
Could you please share a mesh and the code snipped that allows to reproduce the issue? Thanks.

**Comment by jabrucohee** [comment]
Yes, first of all my operating system is ubuntu linux 22.04

but actually the problem seems to occur with any mesh. 

Try to run the follwoing:

```
 import pymeshlab
 import time

 starttime=time.time()

 ms = pymeshlab.MeshSet()
 ms.create_sphere()
 #ms.generate_splitting_by_connected_components()
 ms.compute_curvature_principal_directions_per_vertex(method="Scale Dependent Quadric Fitting")

 print("The required time was:", time.time()-starttime, "seconds")
```

Well first if you run with the '#' in front of the generate_splitting command, I get the following output:

```
average vertex num in each fit: 17.850468
The required time was: 0.01830911636352539 seconds
```

But if you take the `#` away, the code takes incredibly long. (I interuppted it after 10 sec or so)

**Comment by jabrucohee** [comment]
Hey there, 

I understand that your resources are limited. Unfortunately, the error further persists, with exactly the code that I provided.  I would be very greatful if you still managed to take a look at it.  Thank you very much though
