### ISSUE TITLE
How to set world unit rather than perc.?

### ISSUE THREAD

**Issue by LogWell** [cnr-isti-vclab/PyMeshLab#259]
https://pymeshlab.readthedocs.io/en/latest/filter_list.html?highlight=remesh#meshing_isotropic_explicit_remeshing

I found these two params are based on Percentage, so how to set as the world unit?
```
targetlen : Percentage = 1%
maxsurfdist : Percentage = 1%
```

![20221031_234221](https://user-images.githubusercontent.com/34391447/199049141-b68e841e-4cfa-4759-8aeb-b93f378c2904.png)

**Comment by alemuntoni** [comment]
Using the [AbsoluteValue](https://pymeshlab.readthedocs.io/en/latest/classes/absolute_value.html#absolute-value) class.
Note: it will be renamed in the next version of pymeshlab, although I still don't know when it will be released.
