### ISSUE TITLE
Texture map defragmentation filter not working in pymeshlab

### ISSUE THREAD

**Issue by Mobeen-Invozone** [cnr-isti-vclab/PyMeshLab#262]
Texture map defragmentation filter not working in pymeshlab but its working in meshlab if I import the same obj mesh in meshlab and apply filter on it. The obj mesh has a mtl file with multiple textures applied on the mesh. The sample obj mesh given in pymeshlab repo works with their code but my objs dont. I tried to compare my obj, mtl and textures with theirs but could not find much of a difference. 
Has anyone faced this issue? And can someone help me regarding this?

**pymeshlab code I am using:**
```
import pymeshlab as ml
ms = ml.MeshSet()
#Load a mesh with texture per wedge
ms.load_new_mesh('Ulco_Model_3.obj')
m = ms.current_mesh()
print("Input mesh has", m.vertex_number(), 'vertex and', m.face_number(), 'faces')
ms.apply_texmap_defragmentation(matchingthreshold=2, boundarytolerance=0.2, distortiontolerance=0.5, globaldistortiontolerance=0.025, offsetfactor=5, timelimit = 0)
print("Done with defrag")
ms.save_current_mesh("Out/outdefrag.obj")
```

**Drive Link to my obj mesh:**
https://drive.google.com/drive/folders/19O5tWYC0fL3UrYVS-5x1uCoz4DBRgnqt?usp=share_link

**Comment by Zeeraktahir** [comment]
Toggling on the verbosity of the MeshSet with  `ms.set_verbosity(True)`
I am running into this issue of QPainter not active with the same model:-

![image](https://user-images.githubusercontent.com/112944026/203528555-d0b06299-7503-4ae9-a9bd-0c16f58bb8e3.png)

Anyone facing this issue ? Any solutions ?

**Comment by Mobeen-Invozone** [comment]
Still facing this issue. Its been more than 10 days I have posted this issue and haven't got a reply on this!!

**Comment by alemuntoni** [comment]
MeshLab and PyMeshLab are open source software. I try to look into the many issues I receive whenever I find time. If you didn't get a reply from me, it is because I don't have time to look into this issue right now. I am trying to do my best, sorry if you'll have to wait.
In the meantime, could someone check if the same mesh works fine in the double precision version of MeshLab? 
Thanks.

**Comment by Mobeen-Invozone** [comment]
@alemuntoni I checked the same model with double precision version of MeshLab but it crashes on that as well :( If I convert my textures from 8k to 4k then texture map defragmentation filter works without crash.

**These are my system specs:**
- i9 12900K - 16 cores
- RTX 3090 - 24GB
- RAM 128 GB

How can I make it work with 8k textures? If you can help me debugging this issue I would be really grateful.

Regards,
Mobeen

**Comment by alemuntoni** [comment]
I think that this is just a resource problem: GPU memory is not enough to execute the filter using UV texture coordinates with double precision.
However I can't verify it since I don't have a computer able to open your mesh...
