### ISSUE TITLE
Failed to apply filter, but `print_filter_list` print nothing

### ISSUE THREAD

**Issue by zuodexin** [cnr-isti-vclab/PyMeshLab#263]
I'm using the latest pymeshlab installed through `pip` in docker, but i ran into a problem saying
```
PyMeshLabException: Failed to apply filter: compute_texcoord_parametrization_triangle_trivial_per_wedge
Filter does not exists. Take a look at MeshSet.print_filter_list function.
```
Then I test pymeshlab on Google Colab. The following code print nothing
```
%pip install pymeshlab
import pymeshlab
pymeshlab.print_filter_list()
```

**Comment by zuodexin** [comment]
My PyMeshLab version is v2022.2.post2.

**Comment by zuodexin** [comment]
I recheck my local version is 2021.10. I think this if because my python version is 3.6.x.

By running the following code on Colab which has a version of v2022.2.post2, I can find `compute_texcoord_parametrization_least_squares_conformal_maps` now
```
for filter in pymeshlab.filter_list():
    if "compute" in filter:
        print(filter)
```
Can I compile the latest pymeshlab by myself using python 3.6 ?

**Comment by alemuntoni** [comment]
Sorry for the late reply. Yes, you can build PyMeshLab on your own using python 3.6, it should work (but I cannot guarantee).
