### ISSUE TITLE
ms.apply_filter_script()

### ISSUE THREAD

**Issue by idesignitX** [cnr-isti-vclab/PyMeshLab#264]
Something really bad happened.
Please report this issue on https://github.com/cnr-isti-vclab/PyMeshLab/issues
  File "G:\YILIMachine\face.py", line 41, in <module>
    ms.apply_filter_script()
![image](https://user-images.githubusercontent.com/53498745/203883384-b393ca47-4db9-4691-a1a7-7cb676565926.png)

**Comment by alemuntoni** [comment]
Cannot replicate. 
Could you please share
- version of meshlab used to generate the filter script
- version of pymeshlab
- the filter script
- the input mesh used
- the python script that generates the error
