### ISSUE TITLE
ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'

### ISSUE THREAD

**Issue by TasminSarkany** [cnr-isti-vclab/PyMeshLab#266]
Hi! I have installed pymeshlab and I'm trying to use it in a Jupyter notebook. However when I call `import pymeshlab` I get the error `ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'`.

I have used pymeshlab before and never got this error, so I'm confused as to why it's happening. Having looked at some other posts it seems like Anaconda may be an issue and I am using a Miniconda environment (so that I can use the Jupyter notebook), but I installed using pip. The fact that it was working before also suggests to me that this may not be a conda issue. When I go into `Miniconda3\Lib\site-packages` I have Python scripts `__init__`, `polyscope_functions` and `replacer` but not `pmeshlab`. Thanks very much in advance for your help!

**Comment by alemuntoni** [comment]
If the `pmeshlab` module is missing, it means that something in the installation process did not work.
When the pymeshlab wheel is extracted, all the pymeshlab files (included the module) should be placed in the `site-packages/pymeshlab` folder. I don't know how `miniconda` manages installations, but it seems that something is going wrong in the process.

**Comment by alemuntoni** [comment]
About that, I was thinking to create a separated package called `pymeshlab_float` to ship with the next pymeshlab release. It won't fit well with python since it uses only double precision floating points, but it could be useful in this kind of situations, I think.

**Comment by TasminSarkany** [comment]
Thank you for your reply! I'll have a look.

**Comment by jcraz** [comment]
I have met the same question and I don't know how to solve it. I have installed the newest version of Python. I guess it may have some influence.

> "C:\Program Files\Python311\python.exe" C:\Users\asus\pythonProject\1.py 
Traceback (most recent call last):
  File "C:\Users\asus\pythonProject\1.py", line 1, in <module>
    import pymeshlab
  File "C:\Program Files\Python311\Lib\site-packages\pymeshlab\__init__.py", line 11, in <module>
    from .pmeshlab import *
ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'

**Comment by v4r4rth** [comment]
Same issue here -

  File "/usr/local/lib/python3.8/dist-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'

Is there any linux commandline argument I could try to install the right version of pymeshlab?

pip install pymeshlab==2023.12 

^This does not seem to work either
