### ISSUE TITLE
is PyMeshLab not compatible with the latest Python 3.10/3.11 release?

### ISSUE THREAD

**Issue by lanxinger** [cnr-isti-vclab/PyMeshLab#268]
Tried a pip install but got 2 errors:
ERROR: Could not find a version that satisfies the requirement pymeshlab (from versions: none)
ERROR: No matching distribution found for pymeshlab

**Comment by josephaaroncampbell** [comment]
I'm having the same issue. 

`python -m pip install pymeshlab`

> Defaulting to user installation because normal site-packages is not writeable
> ERROR: Could not find a version that satisfies the requirement pymeshlab (from versions: none)
> ERROR: No matching distribution found for pymeshlab

Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32

**Comment by danwbean** [comment]
I am having the same issue/error message after a clean install of python 3.11.1

**Comment by zeerakt** [comment]
Hi, pymeshlab is working fine on python versions prior to 3.11 (working for both 3.10 and 3.9). I checked the release files of pymeshlab and python 3.11 .whl is missing...
Two solutions you can try: 
1- Try to build the source files using Github Actions in your own fork, it will automatically build the newest version including python version 3.11, next download the .whl file and `pip install [package-name].whl` 
2- Use python 3.10 or 3.9 environment until pymeshlab team releases the newer version

**Comment by danwbean** [comment]
Thanks for the quick reply.

Dan

**Comment by danwbean** [comment]
Reverting to python 3.10 solved the current problem.  Thanks.

Dan Bean

**Comment by alemuntoni** [comment]
We did not released pymeshlab for python 3.11 yet. We will soon. 
I'll write here when a new post-version with 3.11 support will be added.
In the meantime, we are already shipping nightly builds for python 3.11. You can download the `pymeshlab_whl*` package from [here](https://github.com/cnr-isti-vclab/PyMeshLab/actions/runs/3874977923) (or any recent github actions run) and install it using pip.

**Comment by danwbean** [comment]
Alessandro,

Thanks for the update.  Everything is working fine with 3.10.

Pymeshlab is a great set of tools.  Your excellent work on it is greatly
appreciated.

Dan Bean
