### ISSUE TITLE
U3D exporter not working

### ISSUE THREAD

**Issue by alemuntoni** [cnr-isti-vclab/PyMeshLab#27]
Given the messy and definitely non-dynamic library load system of the external u3d exporter, the call  
```
ms.save_current_mesh('file.u3d')
```
fails raising a PyMeshLabException.

See #25

**Comment by bdf-imbio** [comment]
Note the workaround described in the linked discussion results in `u3d` files with no color. This could be related to #42

**Comment by alemuntoni** [comment]
I'm happy to finally close this issue.
u3d exporter now works fine on all the platforms, both on MeshLab and PyMeshLab.
The fix will be available in the next post release and in the next releases of PyMeshLab, or you can try it by downloading and installing the last nighly artifact of the Github actions.
