### ISSUE TITLE
.u3d file export not working on docker container with ubuntu image

### ISSUE THREAD

**Issue by sahana-maddali** [cnr-isti-vclab/PyMeshLab#272]
What needs to be done in order to install pymeshlab on docker with fresh Ubuntu base image?

I installed and tested the nightly build outside the docker container and it works perfectly. After running a short python script, .u3d and .tex files are saved to disk.

While trying to recreate the setup inside the docker container, it fails to write out .u3d file only. The .tex file gets written to disk, and it appears as though writing of the .u3d file is skipped, because it exits without a comment or an error.

**Comment by alemuntoni** [comment]
I actually don't know... Nothing should change from outside and inside the docker container. 
This issue is really hard to debug.
Are you using relative or absolute path in the output filename argument? Could you please share your script?
