### ISSUE TITLE
scale dependent quadric fitting does not work after splitting into connected components

### ISSUE THREAD

**Issue by jabrucohee** [cnr-isti-vclab/PyMeshLab#274]
Hey there, 

my original bug report was marked as stale, though I don't understand why. I do understand that your resources are limited. Hence, Herewith I would like to repost it. In case somebody gets a chance to take a look at it later on. 

The code that makes difficulties is 

 import pymeshlab
 import time

 starttime=time.time()

 ms = pymeshlab.MeshSet()
 ms.create_sphere()
 #ms.generate_splitting_by_connected_components()
 ms.compute_curvature_principal_directions_per_vertex(method="Scale Dependent Quadric Fitting")

 print("The required time was:", time.time()-starttime, "seconds")

The output is

`average vertex num in each fit: 17.850468
 The required time was: 0.01830911636352539 seconds`

But when I remove the # in front `ms.generate_splitting_by_connected_components()`

The required time is much longer. I have always interrupted the calculation after several minutes.

**Comment by jabrucohee** [comment]
PS. I don't seem to understand hoe cod highlighting works

**Comment by alemuntoni** [comment]
Closing this as duplicated of #256.
I'll look into it ASAP, sorry for the late reply.
