### ISSUE TITLE
Is there any sample code in pymeshlab to estimate radius from density for point cloud?

### ISSUE THREAD

**Issue by vipasyan** [cnr-isti-vclab/PyMeshLab#279]
I have estimated the radius from density in meshlab application filters for the point cloud. But I could not find any similar documentation in pymeshlab. If there is any please let me know.

Thanks in advance

**Comment by cignoni** [comment]
Look at the function compute_custom_radius_scalar_attribute_per_vertex

https://pymeshlab.readthedocs.io/en/latest/filter_list.html?highlight=radius#compute_custom_radius_scalar_attribute_per_vertex
