### ISSUE TITLE
A question about the source code

### ISSUE THREAD

**Issue by lanzehua** [cnr-isti-vclab/PyMeshLab#281]
In the file :pymeshlab/__init__.py,line11,there is a code line

```
from .pmeshlab import *
```
but I cannot find any file named pmeshlab.py or other,could u please tell me what i can do to deal with that?

**Comment by alemuntoni** [comment]
pmeshlab is the module that is built from the c++ source code of pymeshlab, that is in the `src` folder. Please refer to the github actions to see how pymeshlab is built.
