### ISSUE TITLE
2022.2.post3 saves dummy texture instead of actual texture

### ISSUE THREAD

**Issue by tillns** [cnr-isti-vclab/PyMeshLab#285]
Hi

I had to downgrade from version 2022.2.post3 to 2022.2.post2, because when importing and exporting an obj mesh, a dummy texture instead of the actual texture got saved. Following commands should be enough to reproduce the bug:

`ms = pymeshlab.MeshSet()
ms.load_new_mesh("FOLDER/STRUCTURE/my_mesh.obj")
ms.save_current_mesh("OTHER/OR/SAME/FOLDER/STRUCTURE/my_mesh.obj")`

It doesn't help to add the argument `save:textures=True` to the save function. The dummy texture that is then saved looks as follows:
![dummy](https://user-images.githubusercontent.com/11144916/225556862-865a8550-807a-4d1c-80db-c69386a807a1.png). When I used version 2022.2.post2, the actual texture is saved.

**Comment by ubt0001** [comment]
I have the same issue. When set meshset verbose to true, there is one log message that indicate the texture jpg file fails to load.

**Comment by tillns** [comment]
> can't replicate this issue. Could you please share the OS you are using and an input model with a script that reproduces the issue? Are the paths relative or absolute?

Not allowed to share the model, unfortunately. I already wrote an example script above, so these three commands should be enough to replicate the issue. The path is absolute. Python version is 3.9, OS is Ubuntu 22.04. I have several other mesh processing libraries installed in the same environment. Here is my complete setup to install all dependencies.

`conda create -n CUSTOM_NAME python=3.9
conda activate CUSTOM_NAME
pip install pymeshlab==2022.2.post2 open3d==0.16
conda install -c conda-forge menpo3d scikit-learn scikit-sparse trimesh tqdm pyyaml addict pandas plyfile pyrr natsort networkx gitpython rtree tabulate snakeviz
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`

Replace with pymeshlab==2022.2.post3 to replicate issue.

**Comment by alemuntoni** [comment]
Could you please try to install the nightly wheel from here? https://github.com/cnr-isti-vclab/PyMeshLab/actions/runs/4531413333
I think that the problem was caused by an external change that make the deployment fail (silently...).
If it works, I'll release a new post release soon (today or monday)
