### ISSUE TITLE
Absolute vs. relative paths on Obj export

### ISSUE THREAD

**Issue by gjcope** [cnr-isti-vclab/PyMeshLab#290]
When using save_current_mesh() to save as an .obj, I have to provide a fully qualified path as the file_name parameter or my .obj will be saved in the working directory of the process spawning PyMeshLab rather than the directory the input came from.

This works fine, but when the .mtl reference is made in the obj, it looks to just append file_name which results in a malformed line in my case. Something like "mtllib ./D:\dpo-cook\server\work\6802e8ac-5449-d6a7-4d48-cf4221619771\testset-ga.obj.mtl" where the expected well-formed result would be "mtllib ./testset-ga.obj.mtl"

**Comment by alemuntoni** [comment]
Hi, are you using the last pymeshlab version (2022.2.post3)? This bug should be already solved in that version.
If it still persists, please share more details, like the mesh, the script and the platform you are using.

**Comment by gjcope** [comment]
Sorry, missed there was a new version. I was one behind. It is fixed for me in 2022.2.post3. Thanks!
