### ISSUE TITLE
Merging Meshsets

### ISSUE THREAD

**Issue by tomer-grin** [cnr-isti-vclab/PyMeshLab#302]
I am trying to merge meshsets.
but for some reason they are misligned.
Prior to that I do ICP, break down one of the meshes (CC) and then adding them to a new mesh.
How can I perform this type of operation?

Maybe bounding boxes are different between meshsets?

**Comment by alemuntoni** [comment]
how are you performing the merge operation? could you please provide input meshes and a script that allows to reproduce the issue?

**Comment by tomer-grin** [comment]
> how are you performing the merge operation? could you please provide input meshes and a script that allows to reproduce the issue?

I don't have the exact example anymore.
I think I should have used this piece of code.
https://pymeshlab.readthedocs.io/en/latest/tutorials/apply_filter_parameters_check_default_values.html?highlight=bounding
