### ISSUE TITLE
applying texture png to ply

### ISSUE THREAD

**Issue by anasel01** [cnr-isti-vclab/PyMeshLab#310]
i  use openmvg and openmvs to get 3d model by take photo to object ,after that i got three files : scene_dense_mesh_refine_texture.png and scene_dense_mesh_refine_texture.ply and  scene_dense_mesh_refine_texture.mvs .
can i combine it to get just one file that content the 3D model  without need this three files ? thanks

**Comment by alemuntoni** [comment]
That's not a pymeshlab issue. For this kind of questions, please use stackoverflow or similar forums.
