### ISSUE TITLE
Malformed file for STL import

### ISSUE THREAD

**Issue by ruggieroguida** [cnr-isti-vclab/PyMeshLab#311]
Meshlab 2022.02 on macOS (apple silicon) Monterey 

I am experiencing a weird behaviour with an STL file. 

```
solid obstructions
facet normal 0.0 0.0 1.0
  outer loop
    vertex -167.81942159985445 42.41604121457672 49.76000000000001
    vertex -219.65942159985445 118.83604121457672 49.76000000000001
    vertex -219.65942159985445 42.41604121457672 49.76000000000001
  endloop
endfacet
facet normal 0.0 0.0 1.0
  outer loop
    vertex -219.65942159985445 118.83604121457672 49.76000000000001
    vertex -167.81942159985445 42.41604121457672 49.76000000000001
    vertex -167.81942159985445 118.83604121457672 49.76000000000001
  endloop
endfacet
endsolid obstructions
```

If you try to import this file when you open Meshlab it will fail (Malformed file). If you create a new empty project and try again, it works. I have tried several times and the behaviour is always the same. This is the console output

```
Error: File /Users/ruggiero/Downloads/testmesh.stl has not been loaded
All files opened in 13065 msec
Opened mesh /Users/ruggiero/Downloads/testmesh.stl in 48 msec
All files opened in 3251 msec
```

If you then try a third time it fails again. It works on the forth and so on...

I have also tested it on Ubuntu 20.04 with pyMeshLab 2022.2.post3 (amazing tool BTW) and it fails all the time.

```
ms = pymeshlab.MeshSet()
ms.load_new_mesh(filepath)
```

But, if I reduce the number of digits to 3 maximum, then it loads without any issue.

```
solid obstructions
facet normal 0.0 0.0 1.0
  outer loop
    vertex -167.819 42.416 49.760
    vertex -219.659 118.836 49.760
    vertex -219.65 42.416 49.760
  endloop
endfacet
facet normal 0.0 0.0 1.0
  outer loop
    vertex -219.659 118.836 49.760
    vertex -167.819 42.416 49.760
    vertex -167.819 118.836 49.760
  endloop
endfacet
endsolid obstructions
```

I have also attached the actual file. 

[testmesh.stl.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/11913455/testmesh.stl.zip)

Any idea of what it is going on?

**Comment by ruggieroguida** [comment]
Apologies, just realised that I created the issue in pyMeshLab instead of the MeshLab repo. I saw this issue over there as well. 

It does happen in pyMeshLab as well though.

**Comment by ruggieroguida** [comment]
I can also confirm that, in pyMeshLab (Ubuntu), if you increase the file size by adding a long text to the solid name, as suggested in the other repo, it works.

**Comment by alemuntoni** [comment]
Hi, thanks for reporting.
This issue has been already solved in the codebase and it will be available in the next version of MeshLab.
We are waiting the end of the development of some new plugins to release it, hope it will happen soon.
In the meantime, you can always download one of the last nighly version of [meshlab](https://github.com/cnr-isti-vclab/meshlab/wiki/How-to-install-the-last-nightly-version) or [pymeshlab](https://github.com/cnr-isti-vclab/PyMeshLab/wiki/How-to-install-the-last-nightly-version).
