### ISSUE TITLE
`Ambient Occlusion` crashed on Ubuntu-18.04

### ISSUE THREAD

**Issue by ZhiyeTang** [cnr-isti-vclab/PyMeshLab#312]
OS: Ubuntu-18.04
Python Version: Python-3.8.16
PyMeshLab Version: 2022.2.post3
[In Conda Env]
When I tried to use filter `ms.compute_scalar_ambient_occlusion(occmode=1)`, os reported a crash with `Aborted (core dumped)`. I tried the same filter on a Windows 10 machine in MeshLab v2022.02, and it works well.

**Comment by ZhiyeTang** [comment]
The same filter works well on the same Ubuntu machine in MeshLab v2022.02, thus I think it is more likely to be a problem about PyMeshLab.

**Comment by alemuntoni** [comment]
Installation trough `conda` is not supported by PyMeshLab.
Note that also ubuntu 18.04 is not supported anymore, therefore I cannot solve this issue in any case.
