### ISSUE TITLE
Output of ICP filter

### ISSUE THREAD

**Issue by kevinmcaughey** [cnr-isti-vclab/PyMeshLab#316]
I have a point cloud I am trying to align and validate against another point cloud from a different instrument. I am trying to align the two point clouds on a subset of the clouds, a "visible" region, and to then compare their alignment on another subset of the clouds, an "invisible" region. 

Is there any way to recover the transform that the ICP algorithm applies to the point cloud, as I could sub-select just the visible regions on both point clouds, perform the ICP algorithm, and then apply the same transform to the invisible regions in order to quantitatively evaluate the two systems against each other?

I think this would be a feature enhancement, as I can't see anything like what I'm describing in the documentation. Apologies if this isn't the right place to raise it though

**Comment by kevinmcaughey** [comment]
For anyone pursuing a solution to the same issue, the transform matrix is retained within the mesh in the meshset, and can be accessed using the command `matrix = meshset.mesh(mesh_id).trasform_matrix()`. This transform matrix can then be applied to the visible layer in the meshset using the following `meshset.apply_filter("set_matrix", matrix)`

**Comment by alemuntoni** [comment]
I can confirm your solution.
Another way, is to freeze the transform matrix contained in the mesh object, by executing the filter [`apply_matrix_freeze`](https://pymeshlab.readthedocs.io/en/latest/filter_list.html#apply_matrix_freeze).
