### ISSUE TITLE
How to use multi-threading for data processing

### ISSUE THREAD

**Issue by yangyang117** [cnr-isti-vclab/PyMeshLab#322]
When performing Boolean operations on STL files, if the file size is large, it takes a long time. How do I enable multithreading?

I tried :
import pymeshlab
# get the maximum number of threads available
max_threads = pymeshlab.max_threads()
# set the maximum number of threads to use
pymeshlab.set_max_threads(4)

or

ms.apply_filter('screened_poisson', threads=8)

but its not working.

**Comment by alemuntoni** [comment]
Just some filters use multi threading for processing, and when it is available, it is enabled by default.
Mesh booleans do not support multi threading.

**Comment by yangyang117** [comment]
ok, thank you
