### ISSUE TITLE
test delete mesh is incorrectly named?

### ISSUE THREAD

**Issue by nmccouat** [cnr-isti-vclab/PyMeshLab#324]
should this be test_delete_mesh rather than test_delete_small_components:

https://github.com/cnr-isti-vclab/PyMeshLab/blob/6e081fdfd69185fd014963b7e927902c12175690/pymeshlab/tests/test_delete_mesh.py#L4

**Comment by alemuntoni** [comment]
Yes, fixed in 4fd862304330029e01a10ba6874b0940219009e5.
Thanks for reporting!
