### ISSUE TITLE
Getting the list of existing custom arrays

### ISSUE THREAD

**Issue by marcomusy** [cnr-isti-vclab/PyMeshLab#327]
Hello, I can add and retrieve custom created arrays of scalars (or vectors).

How do I get the list of current existing custom arrays for both vertices and faces?

Thanks

**Comment by alemuntoni** [comment]
There are the functions in the Mesh class for that (e.g. https://pymeshlab.readthedocs.io/en/latest/classes/mesh.html#pmeshlab.Mesh.face_custom_point_attribute_matrix for per-face scalar attribute).

**Comment by marcomusy** [comment]
that returns a numpy array, not a list of strings of names, my question was how do I know what is available.
