### ISSUE TITLE
Request for ARM64 Architecture Support (e.g., Jetson AGX Orin)

### ISSUE THREAD

**Issue by lvmingzhe** [cnr-isti-vclab/PyMeshLab#329]
Hello,

I was wondering if there are any plans to introduce support for arm64 architectures, specifically devices like the Jetson AGX Orin?

I've successfully installed MeshLab_64bit_fp v2020.03+dfsg1 on my Jetson AGX Orin. Given that the Jetson AGX Orin boasts 64GB of Graphics Memory and runs MeshLab seamlessly, it seems like a viable platform for extended support.

If arm64 support is on the horizon, it would undoubtedly benefit many related projects, such as NeRFStudio.

Thank you for all your incredible efforts on this project. I eagerly await your response.

Best regards,

Lv Mingzhe

**Comment by alemuntoni** [comment]
The problem here is the same of #167. We rely on github actions to build and release the packages, and therefore we can release pymeshlab only for architectures that actions provides. If github will add arm64 runners, we will definitely release pymeshlab on them.

**Comment by lvmingzhe** [comment]
Thanks for your kind reply.

**Comment by n1ckfg** [comment]
Has GitHub got ARM Mac runners now?
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners

**Comment by alemuntoni** [comment]
Larger runners are only available for paying accounts. For open source projects, we still have to wait.

**Comment by gilzoide** [comment]
You can add support for Apple Silicon in CMake using `set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64")`, which would build a multiarch executable that runs on both Intel and Apple Silicon CPUs. I'm pretty sure clang/clang++ on mac Intel can build for arm64 just fine.
