### ISSUE TITLE
Can't call face_face_adjacency_matrix

### ISSUE THREAD

**Issue by cvolpe** [cnr-isti-vclab/PyMeshLab#339]
I have a triangular mesh "m". When I call the above function, I get the following:

m.face_face_adjacency_matrix()
Missing Component Exception -FFAdjacency- 
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.2.2\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 1, in Exec
    def Exec(exp, global_vars, local_vars=None):
  File "<input>", line 1, in <module>
pymeshlab.pmeshlab.MissingComponentException: Missing Component
Number meshes: 1
	Mesh id: 0
	Mesh label: 2146.glb

"Missing Component" is not an exception that the documentation says this function raises. There doesn't appear to be a filter whose purpose is to calculate this information. Am I doing it wrong?

**Comment by alemuntoni** [comment]
The face-face adjacency is not computed by default when loading a mesh, but only when is required.
Right now, you can get the face face adjacency after applying a filter that requires it, like [`get_topological_measures`](get_topological_measures).

**Comment by cvolpe** [comment]
Thanks!
