### ISSUE TITLE
Highlight faces after boolean operator

### ISSUE THREAD

**Issue by XuliaDS** [cnr-isti-vclab/PyMeshLab#344]
Hello !
I was wondering if it is possible to highlight the newly generated faces after performing a boolean operation. 
For example,  in blender, this is something that can be done and I find it very useful to manipulate objects:

![boolean](https://github.com/cnr-isti-vclab/PyMeshLab/assets/33522268/377d7f80-9e06-47fc-be39-e0490aec7eb3)

Many many thanks !

**Comment by alemuntoni** [comment]
There is not an option to do that, but you can do it indirectly.

Before the boolean operation, you could set a face quality value for the two meshes (e.g. in m1 all the faces will have quality = 1, in m2 all the faces will have quality = 2). Then, if you perform the boolean operation with `transfer_face_quality=True`, the resulting mesh will have for each face the quality of the face that generated it (1 or 2 depending on the birth mesh of the face).

**Comment by XuliaDS** [comment]
Hi @alemuntoni 

Awesome!! It worked perfect. Many many thanks! 
I did it on the GUI applying a face quality function of 1 to the cube and 3 to the sphere 

![image](https://github.com/cnr-isti-vclab/PyMeshLab/assets/33522268/cdee92ca-04e0-4cca-9f86-01af6641c710)

Great, now I will script it in pyMeshLab :)

cheers
