### ISSUE TITLE
[Windows] PyMeshLab: "surface_reconstruction_screened_poisson"

### ISSUE THREAD

**Issue by RafalWieclawekTukano** [cnr-isti-vclab/PyMeshLab#35]
Hi,
I have a problem with surface_reconstruction_screened_poisson filter on windows 10.
When I run:
`ms.print_filter_list()`
 surface_reconstruction_screened_poisson filter exist on list:
`	subdivision_surfaces_midpoint
       surface_reconstruction_ball_pivoting
	**surface_reconstruction_screened_poisson**
	surface_reconstruction_vcg
	taubin_smooth`,
but when i run: 
`ms.print_filter_parameter_list('surface_reconstruction_screened_poisson')`
I get response:
`Filter surface_reconstruction_screened_poisson not found.`

When I use this filter  in Meshlab, I will get the expected result:
![image](https://user-images.githubusercontent.com/76095430/102325069-ff82e980-3f82-11eb-9999-5fc4570e929f.png)

 
but when I run script with this same parameters:
`ms.apply_filter('surface_reconstruction_screened_poisson', cgdepth = 0, confidence = False, depth = 8, fulldepth = 5, iters = 8, pointweight = 4, preclean = True, samplespernode = 1.5, scale = 1.1, visiblelayer = False)`
I get response:
`Depth[0/0]:	Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000	(89.043 MB)	Nodes: 1`
and I get empty mesh, which after saving have 1Kb size.

My plugins:
MeshSet class - list of loaded plugins (48):
	FilterAmbientOcclusion
	FilterCamera
	FilterClean
	FilterColorProjection
	FilterColorProc
	FilterCreate
	FilterCreateIso
	FilterCSG
	FilterDirt
	FilterFractal
	FilterFunc
	FilterGeodesic
	FilterImagePatchParametrization
	FilterIsoParametrization
	FilterLayer
	FilterMeasure
	FilterMeshing
	FilterMLS
	FilterMutualGlobal
	FilterMutualInfo
	FilterPlyMC
	FilterQHull
	FilterQuality
	FilterSample
	FilterSampleDyn
	FilterSampleGPU
	FilterSampling
	FilterScreenedPoisson
	FilterSDFGPU
	FlterSelect
	FilterSSynth
	FilterTexture
	FilterTriOptimize
	FilterUnsharp
	FilterVoronoi
	FilterGlobalRegistration
	IO3DS
	IOBase
	IOBRE
	IOCollada
	IOCTM
	IOExpe
	IOJson
	IOPDB
	IOTRI
	IOTXT
	IOU3D
	IOX3D

**Comment by alemuntoni** [comment]
Thanks for reporting this!
I'll investigate ASAP!

**Comment by alemuntoni** [comment]
@RafalWieclawekTukano could you please share the model that generates the issue?

**Comment by RafalWieclawekTukano** [comment]
In the attachment I am sending the stl file that I used in Meshlab and I get the effect as in the picture in the main post where I reported the problem, but when calling this filter by the python script - no working
[NewModelTest.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/5708600/NewModelTest.zip)

**Comment by alemuntoni** [comment]
Thanks, the issue happens also on Linux. I'll investigate on this!

**Comment by RafalWieclawekTukano** [comment]
Ok. Thanks for fast reaction.

**Comment by alemuntoni** [comment]
Solved! It will be available in the next version of pymeshlab, which will be released soon!
