### ISSUE TITLE
how to assign new value to vertex scale array?

### ISSUE THREAD

**Issue by Mr-Yellow** [cnr-isti-vclab/PyMeshLab#350]
the function vertex_scalar_array() can return vertex quality, but how to assign new value to vertex scale array?

I try to use: m.v_scalar_array = dis_array to assign new array to vertex scale. However, I get an error "pymeshlab.pmeshlab.Mesh' object has no attribute 'v_scalar_array"

**Comment by alemuntoni** [comment]
When a mesh is inside a MeshSet, it can only be modified by filters (e.g. compute_scalar_by_function_per_vertex). You can set manually scalar/quality in a newly created mesh using the Mesh constructor.
