### ISSUE TITLE
QWidget crash

### ISSUE THREAD

**Issue by dave3d** [cnr-isti-vclab/PyMeshLab#36]
I have a simple script that just tries to load an STL and save it as X3d.

```
import pymeshlab as ml

ms = ml.MeshSet()
ms.load_new_mesh('teapot.stl')
ms.save_current_mesh('teapot.x3d')
```

It crashes when I run it

```
% python pymesh-test.py 
PyMeshLab 0.1.6 based on MeshLab 2020.09d
QWidget: Must construct a QApplication before a QWidget
zsh: abort      python pymesh-test.py
```

This happens both on Mac OS X and Linux.  

Am I doing something wrong?  Thanks.

**Comment by alemuntoni** [comment]
Nope, you're doing everything right!
It's just the x3d plugin that shows a dialog in a place where it shouldn't! Thanks for reporting this!

Btw, could you check if the mesh is exported as expected using meshlab?

**Comment by dave3d** [comment]
Yes, the meshlab application converts my STL file to X3D as expected.  Thanks.

**Comment by alemuntoni** [comment]
Ok, great! 
Just to be sure, could you please share your stl file so I can check if now the issue is solved?

**Comment by dave3d** [comment]
You can get the model here:

https://github.com/dave3d/models/blob/master/teapot.stl

**Comment by dave3d** [comment]
FYI, I compiled the latest PyMeshLab, and it doesn't crash now, but I do get the following error:

```
PyMeshLab 0.1.6 based on MeshLab 2020.12d
Traceback (most recent call last):
  File "pymesh-test.py", line 7, in <module>
    ms.save_current_mesh('teapot.x3d')
pymeshlab.pmeshlab.PyMeshLabException: Unable to save file: teapot.x3d
```

A file teapot.x3d of size 0 was created, but it looked like it failed to actually write to the file.

I tried to save to a variety of other formats (obj, ply, stl, wrl) and they all worked fine.

**Comment by alemuntoni** [comment]
did you try [this](https://github.com/cnr-isti-vclab/PyMeshLab/actions/runs/428498382) one?
there was an issue regarding save parameters: apparently, x3d cannot be saved with both vertex and face normals, for example.
I solved it in that commit, and that should work...

**Comment by dave3d** [comment]
That version that you linked to works for me.  Thanks for the fix.
