### ISSUE TITLE
Unable to install latest version with pip

### ISSUE THREAD

**Issue by AlexMcSD** [cnr-isti-vclab/PyMeshLab#364]
I am unable to install the latest version (2023.12.post1) version of pymeshlab to a remote system using pip. When I use Python 3.11.8 the 2022.2.post3 version is installed, and when I tried using a later version of python (3.12) pip cannot find any distribution of pymeshlab.

I need this specific version as I need to use the generate_alpha_wrap() filter, which I believe is only available on the latest version.

**Comment by geophpherie** [comment]
Are you on a M1/M2/M3 mac?

**Comment by eddjharrison** [comment]
Same, on M2:

```
pip install pymeshlab
ERROR: Could not find a version that satisfies the requirement pymeshlab (from versions: none)
ERROR: No matching distribution found for pymeshlab
```

**Comment by alemuntoni** [comment]
Please see: https://github.com/cnr-isti-vclab/PyMeshLab/issues/167

**Comment by AlexMcSD** [comment]
Sorry for the delay. I am installing on linux on both systems, not Mac. I tried all of the linux wheels for the different python versions in #167 and they failed to work, as they were not supported on the remote system. Previous versions of PyMeshLab were, has something changed in the new release?

**Comment by alemuntoni** [comment]
From 2022.2.post3 to any newer version, the minimum required glibc version is changed. 
Starting from 2022.2.post4, the minimum version is 2.31, that is the default version on ubuntu 20.04 (latest still supported LTS). You need to comply with these requirements to install any recent version of pymeshlab, otherwise you'll need to build it by yourself in your machine.

**Comment by AlexMcSD** [comment]
Yes this seems to be the problem, glibc is 2.35 on my machine and 2.28 on the cluster. Thank you I'll see if I can resolve it from here.

**Comment by msgtobala** [comment]
I am still facing the issue in Ubuntu. I have Ubuntu 22.04 LTS, Python version 3.13.0, and I am trying to install pymeshlab 2025.7
I am getting Error: No matching distributions found for pymeshlab==2025.7

**Comment by alemuntoni** [comment]
See #438
