### ISSUE TITLE
apply filter returns empty

### ISSUE THREAD

**Issue by SerdarHelli** [cnr-isti-vclab/PyMeshLab#369]
import pymeshlab 
 
ms = pymeshlab.MeshSet() 
ms.load_new_mesh("pred_00010388_68220_13_extracted.obj")
ms.load_new_mesh('31.obj')  
res_dict = ms.apply_filter('compute_scalar_by_distance_from_another_mesh_per_vertex', measuremesh =1, refmesh =0 )

res_dict  return s empty

**Comment by alemuntoni** [comment]
Please [**read the docs**](https://pymeshlab.readthedocs.io/en/latest/intro.html).
