### ISSUE TITLE
Missing filter_sketchfab on windows

### ISSUE THREAD

**Issue by alemuntoni** [cnr-isti-vclab/PyMeshLab#37]
Sketchfab plugin does not correctly link to Qt5Qml.dll when loaded from pymeshlab, therefore the filter is missing.

**Comment by pidou46** [comment]
Hello,
Bug still active.
Is there an easy workaround ?

**Comment by alemuntoni** [comment]
Yes, it is still active and there is no easy workaround, sorry. The only workaround is to use the filter on linux or macos.
I'll try to fix this before the next pymeshlab version.

**Comment by alemuntoni** [comment]
Fixed, filter sketchfab will be available also on windows from version 0.2.1
