### ISSUE TITLE
Method face_face_adjacency_matrix() returns odd values

### ISSUE THREAD

**Issue by misan** [cnr-isti-vclab/PyMeshLab#375]
I am trying to determine the neighbors of a given face on a triangular 3D mesh using PyMeshLab. 

I saw the face_face_adjacency_matrix() I could trace back to Meshlab's [source](https://github.com/cnr-isti-vclab/meshlab/blob/b0767f5939e28aeb16b58e033b14708454c9cfa2/src/common/utilities/eigen_mesh_conversions.cpp#L1182) and from there to VCGLib code.

I saw #339 where I learned the need to call get_topology_measures filter before using that method. 

I see the output is a num_faces*3 matrix. I was expecting the content of that matrix's cells to be face numbers. But only 0,1, or 2 values are given in the resulting matrix cells, which I reckon is wrong. 

Having said that, I have failed to find any further explanation about the expected output.

Similar results are obtained in Windows 10 and Linux pymeshlab-2023.12.post1

Sample output:

`array([[1, 2, 0],
       [0, 1, 2],
       [1, 2, 2],
       ...,
       [0, 2, 1],
       [2, 1, 1],
       [0, 2, 0]], dtype=int32)`

**Comment by misan** [comment]
Reading at the moment [this info](http://vcglib.net/adjacency.html), it starts to make some sense.

**Comment by misan** [comment]
I would be able to retrieve the actual face numbers of the neighbors if I had access to face.FFp(j), which I am not sure is offered by pymeshlab.

**Comment by alemuntoni** [comment]
That was a bug! Thanks for reporting.
It should be fixed now.
