### ISSUE TITLE
Potential bug in python pmeshlab.Mesh class __init__ relating to texture coordinates

### ISSUE THREAD

**Issue by nikolas-claussen** [cnr-isti-vclab/PyMeshLab#387]
When initialized using a list of faces, (the `face_list_of_indices` argument), `pmeshlab.Mesh` mangles texture information (passed via the `v_tex_coords_matrix` argument).  Example:

```
vertices_test = np.array([0.0,0.0,0])
textures_test = np.array([0.5,0.5])

mesh_test = pymeshlab.Mesh(vertex_matrix=vertices_test, 
                           face_list_of_indices=[],
                           v_tex_coords_matrix=textures_test)

mesh_test.vertex_tex_coord_matrix()
```
returns `array([[0., 0., 0.]])`

What erroneous texture is returned by `mesh_test.vertex_tex_coord_matrix()` appears to depend on the datatype of the provided texture, with results being either 0 or very large numbers.

If you use the `face_matrix` argument for initialization, there is no problem.

**Comment by alemuntoni** [comment]
Thanks for reporting! This fix will be available in the next pymeshlab version.
