### ISSUE TITLE
Segfault calling Mesh constructor in certain containers

### ISSUE THREAD

**Issue by pyushkevich** [cnr-isti-vclab/PyMeshLab#392]
I am experiencing a strange error when using pymeshlab in containers. When calling `m=pymeshlab.Mesh()` I get a segfault, which gcc shows occurring somewhere deep in pybind11 code.

Here are steps to recreate

```sh
docker run -it debian:bullseye /bin/bash
apt-get update
apt-get install -y python3 pip mesa-common-dev libglu1-mesa-dev
pip install pymeshlab
python3
>>> import pymeshlab
>>> m=pymeshlab.Mesh()
Segmentation fault (core dumped)
```

The segfauly also occurs if calling with parameters:
```python
import pymeshlab
ms=pymeshlab.MeshSet()
ms.load_new_mesh('bunny10k.obj')
v=ms.current_mesh().vertex_matrix()
f=ms.current_mesh().face_matrix()
m=pymeshlab.Mesh(vertex_matrix=v, face_matrix=f)
```

Oddly it occurs regardless of the pymeshlab version I use, including latest build, 0.2.1 and 2022.2

I tried building pymeshlab from source in Debug mode in the container and still get the same segfaults. I was unable to pinpoint the problem with gdb, it seems to have to do with pybind11 and translation between python arrays and eigen vectors, but I am not sure.

**Comment by alemuntoni** [comment]
See https://github.com/cnr-isti-vclab/PyMeshLab/issues/396. I will ship a new release soon that supports numpy>=2.0
