### ISSUE TITLE
csg_operation results in runtime error: Unable to cast Python instance to C++ type

### ISSUE THREAD

**Issue by ferguras** [cnr-isti-vclab/PyMeshLab#40]
I would like to union a mesh, but i got a runtime error instead.
My example code:
import pymeshlab as ml
ms=ml.MeshSet()
ms.load_new_mesh('test.stl')
ms.apply_filter('transform_rotate',rotaxis=0,rotcenter=0,angle=33)
ms2=ml.MeshSet();
ms2.load_new_mesh('test.stl')
ms2.apply_filter('csg_operation',firstmesh=ms,secondmesh=ms2,operator=1)
ms2.save_current_mesh('union.stl')

**Comment by alemuntoni** [comment]
A MeshSet is a set, therefore it can contain more than one mesh. You can see that as a "MeshLab session", containing all the meshes that you load and applying the filters on the selected layer (the "current" mesh).

Therefore, you don't need to have two MeshSets. 
Moreover, as you can read in the [documentation](https://pymeshlab.readthedocs.io/en/latest/filter_list.html#csg_operation), `firstmesh` and `secondmesh` paramters are integers, and they are the id of the mesh inside the MeshSet.

This should work:
```
import pymeshlab as ml
ms=ml.MeshSet()
ms.load_new_mesh('test.stl')
ms.apply_filter('transform_rotate',rotaxis=0,rotcenter=0,angle=33)
ms.load_new_mesh('test.stl')
ms.apply_filter('csg_operation',firstmesh=0,secondmesh=1,operator=1)
ms.save_current_mesh('union.stl')
```
