### ISSUE TITLE
ModuleNotFoundError: No module named 'pymeshlab.pmeshlab'

### ISSUE THREAD

**Issue by Huangkangxian** [cnr-isti-vclab/PyMeshLab#401]
I use Linux and a Python 3.8 virtual environment. 
I installed the pymeshlab==2023.12.post1 through:
git clone https://github.com/cnr-isti-vclab/PyMeshLab.git
cd PyMeshLab
pip install .

And I met this problem:
Traceback (most recent call last):
  File "/home/_test/1-hkx/Code//main.py", line 14, in <module>
    from gs_renderer import Renderer, MiniCam
  File "/home/_test/1-hkx/Code//gs_renderer.py", line 18, in <module>
    from mesh_utils import decimate_mesh, clean_mesh
  File "/home/_test/1-hkx/Code//mesh_utils.py", line 2, in <module>
    import pymeshlab as pml
  File "/home/.conda/envs/dreamgs/lib/python3.8/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ModuleNotFoundError: No module named **'pymeshlab.pmeshlab'**

Please tell me how to fix it,  thanks

**Comment by alemuntoni** [comment]
Do not install pymeshlab trough clone and `pip install .`
That's not the way the project should be installed. The build phase is much more complicated and you can look at the CI workflows, if you really need to build it by yourself.
Otherwise, just run `pip install pymeshlab`.

**Comment by Huangkangxian** [comment]
> Do not install pymeshlab trough clone and `pip install .` That's not the way the project should be installed. The build phase is much more complicated and you can look at the CI workflows, if you really need to build it by yourself. Otherwise, just run `pip install pymeshlab`.

Thank you !!
