### ISSUE TITLE
just import pymeshlab will get Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by HEasoner** [cnr-isti-vclab/PyMeshLab#409]
I test it just by running this code:
import pymeshlab
will get import pymeshlab

pip list:

accelerate                1.2.0
addict                    2.4.0
aiofiles                  23.2.1
aiohappyeyeballs          2.4.4
aiohttp                   3.11.10
aiosignal                 1.3.1
anaconda-anon-usage       0.4.4
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     4.7.0
archspec                  0.2.3
asttokens                 2.0.5
astunparse                1.6.3
attrs                     23.1.0
beautifulsoup4            4.12.3
boltons                   23.0.0
Brotli                    1.0.9
certifi                   2024.7.4
cffi                      1.16.0
chardet                   4.0.0
charset-normalizer        2.0.4
click                     8.1.7
coloredlogs               15.0.1
conda                     24.5.0
conda-build               24.5.1
conda-content-trust       0.2.0
conda_index               0.5.0
conda-libmamba-solver     24.1.0
conda-package-handling    2.3.0
conda_package_streaming   0.10.0
cryptography              42.0.5
dataclasses-json          0.6.7
datasets                  3.2.0
decorator                 5.1.1
Deprecated                1.2.15
diffusers                 0.27.2
dill                      0.3.8
distro                    1.9.0
dnspython                 2.6.1
docker-pycreds            0.4.0
executing                 0.8.3
expecttest                0.2.1
fastapi                   0.115.6
ffmpy                     0.4.0
filelock                  3.13.1
fire                      0.7.0
flatbuffers               24.3.25
frozendict                2.4.2
frozenlist                1.5.0
fsspec                    2024.6.1
fvcore                    0.1.5.post20221221
gitdb                     4.0.11
GitPython                 3.1.43
gmpy2                     2.1.2
gradio                    5.8.0
gradio_client             1.5.1
h11                       0.14.0
httpcore                  1.0.7
httpx                     0.28.1
huggingface-hub           0.25.1
humanfriendly             10.0
hypothesis                6.108.4
idna                      3.7
imageio                   2.36.1
importlib_metadata        8.5.0
iopath                    0.1.10
ipython                   8.25.0
jaxtyping                 0.2.36
jedi                      0.19.1
Jinja2                    3.1.4
jsonpatch                 1.33
jsonpointer               2.1
jsonschema                4.19.2
jsonschema-specifications 2023.7.1
lazy_loader               0.4
libarchive-c              2.9
libmambapy                1.5.8
lintrunner                0.12.5
llvmlite                  0.43.0
markdown-it-py            3.0.0
MarkupSafe                2.1.3
marshmallow               3.23.1
matplotlib-inline         0.1.6
mdurl                     0.1.2
menuinst                  2.1.1
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
mmcv-full                 1.7.2
more-itertools            10.1.0
mpmath                    1.3.0
multidict                 6.1.0
multiprocess              0.70.16
mypy-extensions           1.0.0
networkx                  3.3
ninja                     1.11.1.1
numba                     0.60.0
numpy                     1.26.0
nvdiffrast                0.3.3
omegaconf                 2.3.0
onnxruntime-gpu           1.20.1
opencv-python             4.10.0.84
opencv-python-headless    4.10.0.84
optree                    0.12.1
orjson                    3.10.12
ort-nightly-gpu           1.15.0.dev20230502003
packaging                 24.1
pandas                    2.2.3
parso                     0.8.3
peft                      0.14.0
pexpect                   4.8.0
pillow                    10.4.0
pip                       24.3.1
pkginfo                   1.10.0
platformdirs              3.10.0
pluggy                    1.0.0
pooch                     1.8.2
portalocker               3.0.0
prompt-toolkit            3.0.43
propcache                 0.2.1
protobuf                  5.29.1
psutil                    5.9.0
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   18.1.0
pycosat                   0.6.6
pycparser                 2.21
pydantic                  2.10.3
pydantic_core             2.27.1
pydub                     0.25.1
pygltflib                 1.16.3
Pygments                  2.15.1
PyMatting                 1.1.13
pymeshlab                 2023.12.post1
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-etcd               0.4.5
python-multipart          0.0.19
pytorch3d                 0.7.8                 /yushenghe-24phd/Unique3D-main/Unique3D-main/pytorch3d
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.30.2
regex                     2024.11.6
rembg                     2.0.60
requests                  2.32.3
rich                      13.9.4
rpds-py                   0.10.6
ruamel.yaml               0.17.21
ruff                      0.8.3
safehttpx                 0.1.6
safetensors               0.4.5
scikit-image              0.24.0
scipy                     1.14.1
semantic-version          2.10.0
sentry-sdk                2.19.2
setproctitle              1.3.4
setuptools                69.5.1
shellingham               1.5.4
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.5
stack-data                0.2.0
starlette                 0.41.3
sympy                     1.12
tabulate                  0.9.0
termcolor                 2.5.0
tifffile                  2024.12.12
tokenizers                0.21.0
tomlkit                   0.13.2
torch                     2.4.0
torch_scatter             2.1.2+pt24cu118
torchaudio                2.4.0
torchelastic              0.2.2
torchvision               0.19.0
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.47.0
trimesh                   4.5.3
triton                    3.0.0
truststore                0.8.0
typeguard                 4.4.1
typer                     0.15.1
types-dataclasses         0.6.6
typing_extensions         4.12.2
typing-inspect            0.9.0
tzdata                    2024.2
urllib3                   2.2.2
uvicorn                   0.32.1
wandb                     0.19.1
wcwidth                   0.2.5
websockets                14.1
wheel                     0.43.0
wrapt                     1.17.0
xxhash                    3.5.0
yacs                      0.1.8
yapf                      0.43.0
yarl                      1.18.3
zipp                      3.21.0
zstandard                 0.22.0

**Comment by PhilLichens** [comment]
Did you ever found out what caused this or how to fix this? I'm getting extactly this with pymeshlab 2023.12.post1, python 3.10 in ubunutu 22.04
