### ISSUE TITLE
'simplification_quadric_edge_collapse_decimation' different result in python script vs meshlab

### ISSUE THREAD

**Issue by madalinaraileanu** [cnr-isti-vclab/PyMeshLab#46]
I applied the same filter with default parameters both using pymeshlab (python script) and Meshlab, obtaining different results. 
Resulting meshes had different number of vertices and triangulation.  I also tried different parameters configuration but I can't obtain the same result.

**Comment by alemuntoni** [comment]
Could you please share the mesh that cause the issue?

Just to be sure, are you using 2020.12 or 2020.12d version of MeshLab? PyMeshLab runs with 2020.12d, therefore this could be a cause of small difference of results. But I would like to check and be sure that this is the case.

**Comment by madalinaraileanu** [comment]
Good morning,
Meshlab version 2020.12 (where can I find 2020.12d download file?)
Pymeshlab version 2012.12d

I attached 3 mesh files:

1 - original mesh - mesh.stl
2 - mesh decimated with meshlab - mesh_dec_01_meshlab.stl
3 - mesh decimated with pymeshlab - mesh_dec_01_pymeshlab.stl

All parameters are set with default values and percentage decimation 10.

You can see different triangulation and different number of vertices (in this case just one point, with different meshes more than 30).

I kindly ask you to use the meshes for the tests but not to publish them.

Thank you.
Madalina Raileanu

________________________________
Da: Alessandro Muntoni <notifications@github.com>
Inviato: martedì 12 gennaio 2021 21:25
A: cnr-isti-vclab/PyMeshLab <PyMeshLab@noreply.github.com>
Cc: Ioana Madalina Raileanu <ioanamadalina.raileanu@mail.polimi.it>; Author <author@noreply.github.com>
Oggetto: Re: [cnr-isti-vclab/PyMeshLab] 'simplification_quadric_edge_collapse_decimation' different result in python script vs meshlab (#46)


Could you please share the mesh that cause the issue?

Just to be sure, are you using 2020.12 or 2020.12d version of MeshLab? PyMeshLab runs with 2020.12d, therefore this could be a cause of small difference of results. But I would like to check and be sure that this is the case.

**Comment by alemuntoni** [comment]
@madalinaraileanu feel free to send me the meshes via email (muntoni.alessandro (at) gmail.com) if you don't want to share them!

**Comment by alemuntoni** [comment]
I can confirm that the difference is caused by the fact that pymeshlab uses double precision floating points for its computations. 
The same result can be obtained using 2020.12d version of meshlab.

**Comment by madalinaraileanu** [comment]
Thank you so much!
Regards

Il giorno 25 gen 2021, alle ore 19:34, Alessandro Muntoni <notifications@github.com> ha scritto:

﻿

I can confirm that the difference is caused by the fact that pymeshlab uses double precision floating points for its computations.
The same result can be obtained using 2020.12d version of meshlab.
