### ISSUE TITLE
CANNOT Save The Texture

### ISSUE THREAD

**Issue by WangWenhao0716** [cnr-isti-vclab/PyMeshLab#52]
Hi, currently, I am trying to "translate" the steps in MeshLab to PyMeshLab. My codes are:
```
import pymeshlab as ml
ms = ml.MeshSet()
ms.load_new_mesh('xxxx.ply')
ms.apply_filter('point_cloud_simplification',samplenum=10000)
ms.apply_filter('compute_normals_for_point_sets')
ms.apply_filter('surface_reconstruction_ball_pivoting')
ms.apply_filter('parametrization_trivial_per_triangle',textdim=2048)
```
All the above codes work well.
Then, in MeshLab, the SAVE method is File---Save Project As....
I think, in PyMeshLab, it may be
```
ms.save_current_mesh('third.obj')
```
However, when I finish the saving method, I run:
```
ms.apply_filter('transfer_vertex_color_to_texture', textname='104-1.png')
```

The feedback is
```
---------------------------------------------------------------------------
PyMeshLabException                        Traceback (most recent call last)
<ipython-input-19-a7f980b148b7> in <module>
----> 1 ms.apply_filter('transfer_vertex_color_to_texture', textname='104-1.png')

PyMeshLabException: Failed to apply filter: transfer_vertex_color_to_texture
Details: Save the mesh before creating a texture
```

In fact, I have saved the texture successfully in MeshLab, however, when I finish the last step to transfer to the PyMeshLab, I meet the above error and cannot fix it by myself.

Thanks for the great project you give and look forward to your reply.

**Comment by alemuntoni** [comment]
Thanks for reporting! This issue has been fixed and will be available in the next version of pymeshlab, which will be relased today!
