### ISSUE TITLE
import_cameras_for_active_rasters_from_file cannot open the file

### ISSUE THREAD

**Issue by ramazanabd** [cnr-isti-vclab/PyMeshLab#54]
I want import bundle file with camera matrices by using 'import_cameras_for_active_rasters_from_file', but ms.apply_filter('import_cameras_for_active_rasters_from_file', importfile='<filename>.out') gives an error by saying "No file to open"

**Comment by alemuntoni** [comment]
Could be an issue related to the parameter type used for input files. 
Could you please share the .out file (and if possible the mesh and the rasters)? They would help on finding the issue.

**Comment by ramazanabd** [comment]
Thanks for the quick reply!
I have followed the same procedure in Meshlab for texturing and it accepts the cameras.out properly. It is just PyMeshlab is not accepting. 
I attached the .out file in txt format.

**Comment by ramazanabd** [comment]
[cameras.txt](https://github.com/cnr-isti-vclab/PyMeshLab/files/5949092/cameras.txt)

**Comment by ramazanabd** [comment]
I seem to overcame the problem by not uploading camera intrinsics separately in bundler format but with rasters and mesh in mlp format. However, I came across another problem with ms.apply_filter('parameterization__texturing_from_registered_rasters')
It gives an error:

pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: parameterization__texturing_from_registered_rasters
Details: Fatal error: **glContext not initialized**

Could you please also check on that?

**Comment by alemuntoni** [comment]
Sorry for the late reply. The issue `glContext not initialized` is the same of #43. It is related to how meshlab code is organized for opengl routines, which highly depend on meshlab GUI (which is not present on pymeshlab for obvious reasons).

**Comment by alemuntoni** [comment]
Solved in the last commit. It will be available in the next version of pymeshlab!

**Comment by ramazanabd** [comment]
Thanks a lot!
