### ISSUE TITLE
Could not find a version that satisfies the requirement pymeshlab

### ISSUE THREAD

**Issue by Nathipha** [cnr-isti-vclab/PyMeshLab#55]
I want to use the same filter for a lot of .obj files and now that meshlabserver.exe was replaced I installed python (so I'm still really new to it).

When I call `pip3 install pymeshlab` in cmd (which was started as admin), it just throws two errors:

> ERROR: Could not find a version that satisfies the requirement pymeshlab
> ERROR: No matching distribution found for pymeshlab

I also downloaded the whl file but when I cd to the folder it's in, then call `pip install pymeshlab-0.1.9-cp39-cp39-win_amd64.whl`, I only get this error:

> pymeshlab-0.1.9-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.

Do I have to download anything else or cd to a specific folder to make `pip3 install pymeshlab` work?

I'm using Win 10 with python version 3.9.1 (`python --version` works) - both the 32bit and the 64bit version show up in `PATH`.

**Comment by alemuntoni** [comment]
That's weird. Could you please check if you are running a 32 or 64bit version of python?

Just run python and type:
```
import struct
print(struct.calcsize("P")*8)
```
and check if prints 32 or 64.

**Comment by Nathipha** [comment]
Thanks for the reply!
Both 32bit and 64bit python are installed and I read that it's supposed to default to 64bit but I started a different library that should only work with 32bit and it worked just fine.
Looks like you're right, it was indeed using the 32bit version. I switched the order in `PATH` (64bit is now on top) and now it works. Thanks!

**Comment by flipphillips** [comment]
As a side note, this happens when using an M1 macOS version, regardless of the python. Here's an anaconda version -

```
❯ pip3 install pymeshlab
ERROR: Could not find a version that satisfies the requirement pymeshlab (from versions: none)
ERROR: No matching distribution found for pymeshlab
❯ python
Python 3.9.16 (main, May 16 2023, 14:27:50) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> print(struct.calcsize("P")*8)
64
```
