### ISSUE TITLE
Screened Poisson surface reconstruction stopping halfway or printing error for wrong normals

### ISSUE THREAD

**Issue by Schlomoh** [cnr-isti-vclab/PyMeshLab#56]
So I've been working on creating a 3d pipeline using PyMeshLab to dramatically reduce the amount of faces of a photo scanned .obj while still keeping the textures. I use the reconstruction as a starting point from where to reduce using the quadratic edge collapse and afterwards 'baking' or transferring the textures from the original to the reconstructed mesh. 
This method worked fine for me when not baking the textures, so only having the model reconstructed and reduced, doing the texturing in blender.

Although everything worked so far, it now suddenly won't run through the reconstruction step.
When having the 'preclean' parameter set to `False` the Error I get is:
```
Traceback (most recent call last):
  File "Main.py", line 434, in <module>
    main()
  File "Main.py", line 415, in main
    mesh.apply_filter(
pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: surface_reconstruction_screened_poisson
Details: Filter requires correct per vertex normals.<br>E.g. it is necessary that your <b>ALL</b> the input vertices have a proper, not-null normal.<br> Try enabling the <i>pre-clean<i> option and retry.<br><br>To permanently remove this problem:<br>If you encounter this error on a triangulated mesh try to use the <i>Remove Unreferenced Vertices</i> filterIf you encounter this error on a pointcloud try to use the <i>Conditional Vertex Selection</i> filterwith function '(nx==0.0) && (ny==0.0) && (nz==0.0)', and then <i>delete selected vertices</i>.<br>
```
When the 'preclean' parameter is set to `True` the resulting  reconstruction step does this:
```
Depth[0/7]:     Evaluated / Got / Solved in:  0,000 /  0,000 /  0,000   (927,133 MB)    Nodes: 1
Depth[1/7]:     Evaluated / Got / Solved in:  0,000 /  0,000 /  0,015   (927,148 MB)    Nodes: 8
Depth[2/7]:     Evaluated / Got / Solved in:  0,000 /  0,001 /  0,001   (927,152 MB)    Nodes: 64
Depth[3/7]:     Evaluated / Got / Solved in:  0,000 /  0,004 /  0,002   (927,504 MB)    Nodes: 512
Depth[4/7]:     Evaluated / Got / Solved in:  0,000 /  0,021 /  0,027   (933,512 MB)    Nodes: 4096
Depth[5/7]:     Evaluated / Got / Solved in:  0,000 /  0,085 /  0,054   (958,969 MB)    Nodes: 32768
Depth[6/7]:     Evaluated / Got / Solved in:  0,000 /  0,007 /  0,023   (958,969 MB)    Nodes: 0
Depth[7/7]:     Evaluated / Got / Solved in:  0,000 /  0,013 /  0,041   (958,969 MB)    Nodes: 0
```
The reconstruction still finishes until the program exits because it cannot find the file after saving it. (Its being saved after simplification and then should be reloaded to bake the textures onto the new mesh).

Since I didn't change a thing concerning the reconstruction I'm kind of dumbfounded as to why this would happen.

**Comment by alemuntoni** [comment]
Hi, sorry for the late reply.
I don't understand what exactly is not working. Are you running something like
```
ms.save_current_mesh('file.obj')
ms.load_new_mesh('file.obj')
```
and it does not find the file in the load? It is not clear in your post.
Could you please share the script that you are running?

**Comment by Schlomoh** [comment]
Hey, thanks so much for trying to help and excuse my late response..

But yeah basically its just loading a mesh and saving it after the screened Poisson reconstruction. Since opening this issue the problem of the reconstruction returning 0 nodes after the depth of 5 just fixed itself. 
But still it only computes the reconstruction if the preclean argument is set to true. No matter what the input obj file is (in this case various photo scanned models). If not set applying the filter always fails because of 'incorrect vertex normals'. Can you think of a consistent way of having the normals 'fixed' before applying the reconstruction filter?

Also when having a textured model, and using the 'transfer_vertex_attributes_to_texture_1_or_2_meshes' filter to bake the high poly geometry onto the low poly mesh as a normal map, is there any way of having the filter generate a tangent space normal map instead of an object space normal map? 

Again thanks a lot for replying and for creating this awesome library!

Best regards
Mo

**Comment by alemuntoni** [comment]
What is the exact error you get when you talk about "incorrect vertex normals"?
Is it complaining because the point cloud does not have vertex normals? Because screened poisson requires non-null vertex normals on all the vertices. If the mesh you load does not have them, you need to compute them in some way. 
Or, with the preclean parameter, all the vertices with non-proper normal are removed.

> Also when having a textured model, and using the 'transfer_vertex_attributes_to_texture_1_or_2_meshes' filter to bake the high poly geometry onto the low poly mesh as a normal map, is there any way of having the filter generate a tangent space normal map instead of an object space normal map?

I am not sure, but I think there is not such filter in meshlab or pymeshlab.
