### ISSUE TITLE
Mesh face area

### ISSUE THREAD

**Issue by tvoesolncee** [cnr-isti-vclab/PyMeshLab#57]
Thank you very much for PyMeshLab! 

I have a question about mesh representation. Is there any possibility to get mesh attributes like triangle area per face? 
I found only whole surface area attribute.

**Comment by alemuntoni** [comment]
You could use the filter `per_face_quality_according_to_triangle_shape_and_aspect_ratio`, with `metric=3` or `metric='Area'`.

Then the area of each face will be saved in the quality of the face, and then you can extract the values with `ms.current_mesh().face_quality_array()` which will return a numpy array with the values.
