### ISSUE TITLE
using pymeshlab in offscreen environment

### ISSUE THREAD

**Issue by flufy3d** [cnr-isti-vclab/PyMeshLab#58]
already setup the xorg server running

pymeshlab.pmeshlab.PyMeshLabException: Failed to apply filter: ambient_occlusion
Details: Fatal error: glContext not initialized

**Comment by alemuntoni** [comment]
#43

**Comment by flufy3d** [comment]
I am okay with always enable the opengl context .
but seems xvfb not work too
xvfb-run -a -s "-screen 0 800x600x24" python3 test.py

is there any quick workaround I can make it work?

**Comment by flufy3d** [comment]
apt install xvfb

Xvfb :5 -screen 0 800x600x24 &
export DISPLAY=:5
glxgears 

with this setting

the glxgears is working now

but the pymeshlab is not working

**Comment by alemuntoni** [comment]
There is no workaround at the moment, sorry.
It is related with how code is organized inside meshlab. I am working on this, but it requires a big refactoring on the code infrastructure.

**Comment by flufy3d** [comment]
thanks anyway

**Comment by alemuntoni** [comment]
Fixed with #61, will be available in the next pymeshlab version!

**Comment by flufy3d** [comment]
Awesome! could you release it to PyPi now?

**Comment by alemuntoni** [comment]
Nope, sorry. I'm not shipping a new version containing just a single bugfix.
I'll release a new version where there will be enough new features.
In the meantime, if you really need this working, you can download the pymeshlab produced by the github actions and use it.
Just go [here](https://github.com/cnr-isti-vclab/PyMeshLab/actions), select your platform and download the package relative to your python version.
Then, extract the archive inside a folder called `pymeshlab`. From outside that folder, you can run pymeshlab.
Before doing this, I would uninstall pymeshlab from pypi first (just to be sure to use the downloaded version). Then you can download it again from pypi when the new version will be shipped.
