### ISSUE TITLE
Installing PyMeshlab on Jetson Xavier

### ISSUE THREAD

**Issue by rakkidi** [cnr-isti-vclab/PyMeshLab#71]
Python 3.6.9

Hello! Lately we have acquired a Jetson Xavier preinstalled with Ubuntu 18.04 and tried to install pymeshlab.
We tried to install it as in the instruction stated with pip, and tried to download the wheel file.
We are always encoutering the error:

`ERROR: No matching distribution found for pymeshlab`
Is it possible that we can't install pymeshlab on an ARM architecture?

**Comment by alemuntoni** [comment]
> Is it possible that we can't install pymeshlab on an ARM architecture?

Exactly. Sorry but ARM architecture is not supported right now.

**Comment by QuentinThisse** [comment]
Hello! Do you plan to support ARM architecture ?

**Comment by alemuntoni** [comment]
No, we are not planning to support ARM. We just don't have resources to make meshlab available on ARM soon.

**Comment by johnnynunez** [comment]
> No, we are not planning to support ARM. We just don't have resources to make meshlab available on ARM soon.

https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/

**Comment by donaldparker** [comment]
I was able to get it to work via `pip3 install git+https://github.com/cnr-isti-vclab/PyMeshLab` on apple arm. Followed this post https://stackoverflow.com/questions/75239944/pymeshlab-not-installing-in-macbook-air-m2
