### ISSUE TITLE
Snapshot command line

### ISSUE THREAD

**Issue by Gassepouille** [cnr-isti-vclab/PyMeshLab#78]
Hi, it's not so much of an issue but more of a question. 

I couldn't find a forum dedicated to pymeshlab, so I posted this here. Forgive me if it's not the right place.

I wanted to know if there was an ongoing work for a basic snapshot possibility in pymeshlab ? 

I read some people were using that filter : "gpu_filter_example_" in meshlabserver 
But I couldn't find or make anything work to get the snapshot going.

**Comment by alemuntoni** [comment]
Hi, right now there is no such feature in pymeshlab, sorry.
You are right about the filte `gpu_filter_example_`, but I think there is still some issue about it and all the other filters that require a GL Context (like #76). I'll investigate and I'll update here as soon as possible.

**Comment by Gassepouille** [comment]
Hey, no worries !
Thanks ! I'll keep an eye out for your updates ! 

Let me know if I can help in any ways!

Cheers

**Comment by alemuntoni** [comment]
I quickly checked the gpu filter example, and it actually works:

```
ms = pymeshlab.MeshSet()
ms.load_new_mesh('bunny.obj')
ms.gpu_filter_example_(imagefilename='bunny.png')
```

The output is a simple 512x512 png image, and you can control the size with the apposite parameters:
https://pymeshlab.readthedocs.io/en/latest/filter_list.html#gpu_filter_example_

Right now there is no way to change the camera direction, sorry :(
Also, in the next version I think that the name of ther filter will change :)

**Comment by Gassepouille** [comment]
Hey, thanks for the update.

I must be doing something wrong : 

I'm running this : 

```
python3 ./app/meshlab/snapshot.py "bunny.obj"
```

snapshot.py 
```
ms = ml.MeshSet()
ms.load_new_mesh(filePath)
ms.gpu_filter_example_(imagefilename='bunny.png')
```

And somehow I get this as a response: 
```
PyMeshLab 0.2 based on MeshLab 2020.12d
Aborted (core dumped)
```
I'm running the script on WSL  if that helps.

I'm so sorry to bother you with this

**Comment by alemuntoni** [comment]
Thank you! :) No bothering at all!
I double checked both on windows and linux, and the filter works.. So it seems to be an issue related with WSL.
This filter uses OpenGL calls, therefore I don't know if WSL actually supports graphics linux libraries...

**Comment by Gassepouille** [comment]
Yeah, I think you're right: The setup seems to work with some other filters without problems but not for this one.
The ultimate goal being to run this on an EC2 instance without GPU that won't work at all, I wasn't thinking :/ 

Thanks for helping me out, and sorry for wasting some of your time -_-'
