### ISSUE TITLE
problem running the script on windows

### ISSUE THREAD

**Issue by HollowHeartNet** [cnr-isti-vclab/PyMeshLab#86]
Hi,

I've installed the library via pip install on windows 10. My Python version is 3.7.9. When I use the library through windows powershell, it works fine. But when I want to run a script, the modules cannot be found. 

for example: `python myscript.py ` --> `AttributeError: module 'pymeshlab' has no attribute 'MeshSet'`

I don't understand what the problem is. Do you know how to solve this? I really would like to run the functions via script. 

Thank you in advance.

**Comment by alemuntoni** [comment]
Could you please share the script? 
It is really difficult to reproduce an issue of a script without having that script...

**Comment by HollowHeartNet** [comment]
Sorry, I forgot to add the script content:

```
import pymeshlab as ml

#Test functions: 
ms = ml.MeshSet()
ms.load_new_mesh('path/to/input')
ms.convex_hull()
ms.save_current_mesh('path/to/output')

```
```
What I get when running the script:
Traceback (most recent call last):
  File ".\pymeshlab.py", line 10, in <module>
    import pymeshlab as ml
  File "C:\Users\rahim\Desktop\fit_plane\pymeshlab.py", line 41, in <module>
    ms = ml.MeshSet()
AttributeError: module 'pymeshlab' has no attribute 'MeshSet'
```

However, when I run the pymeshlab functions via windows terminal (powershell), it works:
```
PS C:\Users\rahim\Desktop> python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import pymeshlab as ml
PyMeshLab 0.2 based on MeshLab 2020.12d
Warning:
Unable to load the following plugins:

        filter_sketchfab.dll: filter_sketchfab.dll does not seem to be a Qt Plugin.

Cannot load library C:\Users\rahim\miniconda3\lib\site-packages\pymeshlab\lib\plugins\filter_sketchfab.dll: Die angegebene Prozedur wurde nicht gefunden.

>>> ms = ml.MeshSet()
>>> quit()
```

I don't understand why it's not working with the script the same way.

**Comment by alemuntoni** [comment]
Could it be related with:

```
Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation
```
?

**Comment by HollowHeartNet** [comment]
I don't think so. I've also used Anaconda Prompt to run the script and I get the same error:

```
(base) C:\Users\rahim\Desktop>python pymeshlab.py
Traceback (most recent call last):
  File "pymeshlab.py", line 10, in <module>
    import pymeshlab as ml
  File "C:\Users\rahim\Desktop\pymeshlab.py", line 41, in <module>
    ms = ml.MeshSet()
AttributeError: module 'pymeshlab' has no attribute 'MeshSet'
```

**Comment by alemuntoni** [comment]
I actually don't know what anaconda does internally to make pymeshlab not woking, 
This is the same issue of #47.
Also, I don't know if this could be related with [this](https://github.com/conda/conda/issues/8126). 
But I'm pretty sure that this is not an issue of the pymeshlab package.

**Comment by HollowHeartNet** [comment]
Funny, I've solved this issue by renaming the python file 'pymeshlab.py' to 'meshlab.py'. Now it works. 
Thank you for the help @alemuntoni
