### ISSUE TITLE
shape_diameter_function results in core dumped error

### ISSUE THREAD

**Issue by rkjones4** [cnr-isti-vclab/PyMeshLab#87]
Hi!

Every-time I try calling the shape_diameter_function (with any parameters, any mesh), I get a core dumped error

**Comment by rkjones4** [comment]
Weirdly, this only happens when I run python from an interactive session -- when I use the same function within a file it doesn't break

**Comment by alemuntoni** [comment]
Hi, sorry for the late reply.

I cannot replicate the issue.
Could you please be more specific to help me on replicate it? 
Could you please share the commands you run and which operative system you are using?
