### ISSUE TITLE
Possibility to get a log of the execution of some filters

### ISSUE THREAD

**Issue by VolDr** [cnr-isti-vclab/PyMeshLab#89]
I skimmed through the documentation, but I couldn't find this feature. 
Some meshlab filters output a log after execution. "Close Holes" filter displays the following message "Closed 14 holes and added 28 new faces", for example.
In meshlab this filter just return None. Is it possible to get this information?

**Comment by alemuntoni** [comment]
You can visualize the output of filters by calling the [`set_verbosity`](https://pymeshlab.readthedocs.io/en/latest/classes/meshset.html#pmeshlab.MeshSet.set_verbosity) function of the MeshSet.
But you are right that the info about number of closed holes and added faces could be useful as ouput dictionary of the filter. I'll add this for the next version of pymeshlab
