### ISSUE TITLE
Progress bar when applying filters in pymeshlab

### ISSUE THREAD

**Issue by oiluigio** [cnr-isti-vclab/PyMeshLab#90]
Hi there,
Is there a way to see the time progression of the computation, when applying a filter? For example something similar to the meshlab GUI version (the % bar bottom right of the screen) or the python tqdm package?
In my specific case I am using the filter uniform_mesh_resampling.

Thanks in advance!

giulio

**Comment by alemuntoni** [comment]
There is the [`set_verbosity`](https://pymeshlab.readthedocs.io/en/latest/classes/meshset.html#pmeshlab.MeshSet.set_verbosity) method of the MeshSet class, that allows to show the output log in the python shell.

**Comment by oiluigio** [comment]
Works like a charm!

Many thanks
