### ISSUE TITLE
methods print_filter_list and filter_parameter_values not working in pymeshlab 0.2.0

### ISSUE THREAD

**Issue by oiluigio** [cnr-isti-vclab/PyMeshLab#91]
Is it possible that print_filter_list is not available as MeshSet method in 0.2.0 (is working in my 0.1.9 install)?
Also filter_parameter_values seems available but causes a crash at each instance (again working fine if I work with 0.1.9)?
I attach a screenshot of ipython shell
![debug_filter_list](https://user-images.githubusercontent.com/38915394/112851686-829bfb80-90ab-11eb-887a-cc5dbdb49c67.png)

thanks in advance

Giulio

**Comment by alemuntoni** [comment]
`print_filter_list` in 0.2 is a module function: https://pymeshlab.readthedocs.io/en/latest/classes/pmeshlab.html

therefore now you can call:
```
pymeshlab.print_filter_list()
```

[`filter_parameter_values`](https://pymeshlab.readthedocs.io/en/latest/classes/meshset.html#pmeshlab.MeshSet.filter_parameter_values) returns a dictionary containing the parameters and their values that would be used by the given filter if it would be applied in the current MeshSet. If the filter requires an input mesh, values are computed starting from that input mesh. Maybe you are running this function in an empty MeshSet?
In any case, it should not crash, I'll check on it.
