### ISSUE TITLE
Segmentation Fault on per_vertex_texture_function

### ISSUE THREAD

**Issue by FilipePires98** [cnr-isti-vclab/PyMeshLab#92]
Python 3.6.9
PyMeshLab 0.2 based on MeshLab 2020.12d

Error: Segmentation fault (core dumped)

Reproduce Code:
```
import pymeshlab as pml

ms = pml.MeshSet()
mesh = o3d.io.read_triangle_mesh("./mesh.obj")
ms.set_current_mesh(0)
ms.per_vertex_texture_function()
```

Mesh Properties:
- \# of Vertices = 25154
- \# of Faces = 49953
- Contains Normals = True
- Contains Colored Faces = True 

I have MeshLab 2020.12 installed and the per_vertex_texture_function filter works on the GUI for the same .obj file.
I am sure that the segmentation fault occurs when per_vertex_texture_function filter is executed.
I am guessing that this is due to the file being too large or something?
Is there a way to increase the maximum memory size usable by pymeshlab in order to avoid this error?

Note:
The issue also occurs with a decimated version of the original mesh (now containing only 282 vertices and 601 faces).

**Comment by FilipePires98** [comment]
I found out what my issue was, I was loading the mesh the wrong way...
If anyone is interested in knowing how to transfer color information from a mesh to a uv texture using pymeshlab, here is my code:

```
    ms = pml.MeshSet()
    ms.load_new_mesh("./filename.obj")
    ms.set_current_mesh(0)
    ms.per_vertex_texture_function()
    ms.convert_pervertex_uv_into_perwedge_uv()
    ms.parametrization_trivial_per_triangle(sidedim=0, textdim=1024, border=0, method='Space-optimizing')
    ms.save_current_mesh(file_name="./filename-textured.obj", save_face_color=False, save_face_normal=True, save_wedge_texcoord=True)
    ms.transfer_vertex_color_to_texture(textname="filename-textured.png", textw=1024, texth=1024, pullpush=True)
```
I hope it is helpful!

**Comment by alemuntoni** [comment]
the call `ms.set_current_mesh(0)` is not necessary. Here there is the [documentation](https://pymeshlab.readthedocs.io/en/latest/index.html) of the library and a [set of tutorials](https://pymeshlab.readthedocs.io/en/latest/tutorials.html).
