### ISSUE TITLE
Interaction with MeshLab GUI

### ISSUE THREAD

**Issue by liushuya7** [cnr-isti-vclab/PyMeshLab#97]
Hi,

May I ask if there is a way to use PyMeshLab to interact with the meshes that are loaded in the MeshLab GUI?

So far I have only discovered [load_project()](https://pymeshlab.readthedocs.io/en/0.1.8/classes/meshset.html?highlight=project#pmeshlab.MeshSet.load_project) and [save_project()](https://pymeshlab.readthedocs.io/en/0.1.8/classes/meshset.html?highlight=project#pmeshlab.MeshSet.save_project), but didn't find a way to interface with a MeshLab GUI application that is running. I am curious because I want to use the Align Tool in the GUI application before executing PyMeshlab scripts.

I am mainly looking for a way to visualize the meshes loaded from PyMeshlab.

Thanks,
Joshua

**Comment by alemuntoni** [comment]
pymeshlab does not provide any visualization tool. It is not the purpose of pymeshlab.
The only way is to use external python libraries, or just meshlab.
To access to mesh data, you can use the methods provided by the [Mesh](https://pymeshlab.readthedocs.io/en/latest/classes/mesh.html) that export data to numpy arrays.
