### ISSUE TITLE
Can not get UV coordinates by PyMeshLab, and model's normal seem not quite right after simplification.

### ISSUE THREAD

**Issue by wityhb** [cnr-isti-vclab/PyMeshLab#98]
Hi, i find your meshLab is very powerful. And now i have three question. 
Firstly, I load a .fbx model which includes UV  coordinates. I want to get uv in numpy array. Code like this:

![image](https://user-images.githubusercontent.com/31581382/115331721-05a30400-a1c9-11eb-91bd-850b79123892.png)

but it seems can not work well. 

![image](https://user-images.githubusercontent.com/31581382/115331777-266b5980-a1c9-11eb-8edc-523e2dced8d1.png)

What should i do?

About model's normals after simplification. Code like this:
![image](https://user-images.githubusercontent.com/31581382/115330786-53b70800-a1c7-11eb-9e0f-cfa52df4b078.png)
the result is:
![image](https://user-images.githubusercontent.com/31581382/115330966-a0024800-a1c7-11eb-8736-9645f386e1aa.png)
The normals of the edge of the model seem not right.

The last one, if model includes uv and uv2, how can i get uv coords numpy array and uv2 coords numpy array respectively. Thank you!

The attachment is a fbx model:
[hasSubModel.zip](https://github.com/cnr-isti-vclab/PyMeshLab/files/6340416/hasSubModel.zip)

**Comment by alemuntoni** [comment]
Hi, about the first problem, textcoords are loaded on per-wedge texture coordinates, and right now there is not the possibility to get per wedge texture coordinates (I'll add this in the next version of pymeshlab).
In the meantime, if it suits for your application, you could do: 
```
ms.convert_perwedge_uv_into_pervertex_uv()
mesh = ms.current_mesh()
mesh.compact()
mesh.vertex_tex_coord_matrix()
```

About the second question, could you check for me if the same unexpected result is obtained using meshlab?

For the third question, for uv2 do you mean that the model has two per-vertex texture coordinate attributes?
As far as I know, meshlab is able to store in a mesh only one per-vertex texture coordinate attribute...

**Comment by wityhb** [comment]
Hi, @alemuntoni,  thanks for your patient answer. I realized something i did not 
express clearly. About second question, the result as i showed in the picture was obtained using meshlab by running 
![image](https://user-images.githubusercontent.com/31581382/115644613-783eeb80-a351-11eb-885e-abd6932b78d9.png)
you maybe get the same reuslt from the attachment's model.

For the third question, maybe i didn't express what i mean. Take .fbx models as an example, now i have a fbx model which have two channels of UV,

![image](https://user-images.githubusercontent.com/31581382/115649239-8abd2300-a359-11eb-8509-474c0f14903f.png)
and
![image](https://user-images.githubusercontent.com/31581382/115649297-a4f70100-a359-11eb-9fcd-abe828457e6a.png)
In my opinion, they represent uv and uv2 respectively. I hope meshlab can get those two channels uv respectively. Thank you!
